<?php

namespace App\Services;

use App\Models\{Category,Customer,CustomerLedger,Invoice,InvoiceItem,Product,ProductVariant,SalesReturnDocument,SalesReturnDocumentItem,StockMovement,Warehouse,WarehouseStock};
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Validation\ValidationException;

class SalesReturnService
{
    public function __construct(private SalesReturnCalculationService $calculator) {}

    public function createDraft(array $data, ?int $actorId): SalesReturnDocument { return DB::transaction(fn()=> $this->persistDraft(new SalesReturnDocument(['document_number'=>$this->nextDocumentNumber(),'status'=>SalesReturnDocument::STATUS_DRAFT,'created_by'=>$actorId]), $data, $actorId)); }
    public function updateDraft(SalesReturnDocument $doc, array $data, ?int $actorId): SalesReturnDocument { if(!$doc->isDraft()) throw ValidationException::withMessages(['document'=>'فقط پیش‌نویس قابل ویرایش است.']); return DB::transaction(fn()=> $this->persistDraft($doc, $data, $actorId)); }
    private function persistDraft(SalesReturnDocument $doc, array $data, ?int $actorId): SalesReturnDocument
    {
        $source=$data['source_type']; $doc->fill(['source_type'=>$source,'customer_id'=>(int)$data['customer_id'],'invoice_id'=>$source===SalesReturnDocument::SOURCE_INTERNAL_INVOICE?(int)($data['invoice_id']??0):null,'external_invoice_number'=>$source===SalesReturnDocument::SOURCE_SAZEH_HESAB?($data['external_invoice_number']??null):null,'external_invoice_date'=>$source===SalesReturnDocument::SOURCE_SAZEH_HESAB?($data['external_invoice_date']??null):null,'default_destination_warehouse_id'=>$data['default_destination_warehouse_id']??null,'return_reason'=>$data['return_reason']??null,'reference_number'=>$data['reference_number']??null,'description'=>$data['description']??null,'updated_by'=>$actorId]); $doc->save();
        $doc->items()->delete(); $items=$source===SalesReturnDocument::SOURCE_INTERNAL_INVOICE?$this->prepareInternalItems($doc,$data):$this->prepareSazehItems($doc,$data); foreach($items as $i=>$attrs){$attrs['sort_order']=$i+1; $doc->items()->create($attrs);} $this->refreshTotals($doc); return $doc->fresh('items');
    }
    public function cancelDraft(SalesReturnDocument $doc, ?int $actorId, ?string $reason=null): SalesReturnDocument { if(!$doc->isDraft()) throw ValidationException::withMessages(['document'=>'فقط پیش‌نویس قابل لغو است.']); $doc->update(['status'=>SalesReturnDocument::STATUS_CANCELLED,'cancelled_by'=>$actorId,'cancelled_at'=>now(),'cancel_reason'=>$reason]); return $doc; }
    public function apply(SalesReturnDocument $document, ?int $actorId): SalesReturnDocument
    { return DB::transaction(function() use($document,$actorId){ $doc=SalesReturnDocument::query()->whereKey($document->id)->lockForUpdate()->firstOrFail(); if($doc->isApplied()) return $doc; if(!$doc->isDraft()) throw ValidationException::withMessages(['document'=>'فقط پیش‌نویس قابل ثبت نهایی است.']); Customer::query()->whereKey($doc->customer_id)->lockForUpdate()->firstOrFail(); if($doc->isInternal()) Invoice::query()->whereKey($doc->invoice_id)->lockForUpdate()->firstOrFail();
            $doc->load('items'); foreach($doc->items as $item){ if($doc->isSazehHesab() && $item->item_source===SalesReturnDocumentItem::SOURCE_NEW_PRODUCT){ $this->materializeNewProduct($item); }
                $item->refresh(); if(!$item->product_variant_id) throw ValidationException::withMessages(['items.'.$item->sort_order.'.product_variant_id'=>'تنوع کالا نامعتبر است.']); $this->recordInventoryEntry($item,$actorId); }
            $this->refreshTotals($doc); $this->recordCustomerCredit($doc,$actorId); $doc->update(['status'=>SalesReturnDocument::STATUS_APPLIED,'applied_by'=>$actorId,'applied_at'=>now()]); return $doc->fresh('items'); }); }

    public function prepareInternalItems(SalesReturnDocument $doc, array $data): array
    { $invoice=Invoice::with('items.product','items.variant')->findOrFail((int)$data['invoice_id']); if((int)$invoice->customer_id !== (int)$data['customer_id']) throw ValidationException::withMessages(['invoice_id'=>'فاکتور متعلق به مشتری انتخاب‌شده نیست.']); if($invoice->status !== Invoice::STATUS_SHIPPED && empty($data['override_invoice_status'])) throw ValidationException::withMessages(['invoice_id'=>'فقط فاکتور ارسال‌شده مجاز است.']); $inputRows=collect($data['items']??[])->keyBy(fn($r)=>(int)($r['invoice_item_id']??0)); $rows=$this->calculator->calculateInternalPreview($invoice,$data['items']??[]); $out=[]; foreach($rows as $r){ $it=$r['invoice_item']; $input=$inputRows->get((int)$it->id, []); $cond=$this->condition($input['item_condition'] ?? null); $wh=$this->resolveDestinationWarehouse($cond,(int)($input['destination_warehouse_id']??0),!empty($data['can_override_destination'])); $out[]=['invoice_item_id'=>$it->id,'product_id'=>$it->product_id,'product_variant_id'=>$it->variant_id,'product_name_snapshot'=>$it->product?->name,'variant_name_snapshot'=>$it->variant?->variant_name,'sku_snapshot'=>$it->variant?->variant_code,'barcode_snapshot'=>$it->variant?->variant_code,'item_source'=>SalesReturnDocumentItem::SOURCE_INVOICE_ITEM,'item_condition'=>$cond,'destination_warehouse_id'=>$wh->id,'sold_quantity_snapshot'=>(int)$it->quantity,'previously_returned_quantity_snapshot'=>$r['previous_quantity'],'return_quantity'=>$r['quantity'],'unit_price_snapshot'=>(int)$it->price,'line_discount_snapshot'=>(int)($it->line_discount_amount??0),'allocated_invoice_discount_snapshot'=>$r['allocated_discount'],'refund_unit_price'=>$r['refund_unit_price'],'refund_amount'=>$r['refund_amount']]; } return $out; }
    public function prepareSazehItems(SalesReturnDocument $doc, array $data): array
    { $out=[]; foreach(($data['items']??[]) as $idx=>$row){ $qty=(int)($row['return_quantity']??0); if($qty<=0) continue; $cond=$this->condition($row['item_condition']??null); $wh=$this->resolveDestinationWarehouse($cond,(int)($row['destination_warehouse_id']??0),!empty($data['can_override_destination'])); $source=$row['item_source']; $unit=(int)($row['refund_unit_price']??0); $attrs=['item_source'=>$source,'item_condition'=>$cond,'destination_warehouse_id'=>$wh->id,'return_quantity'=>$qty,'refund_unit_price'=>$unit,'refund_amount'=>$qty*$unit]; if($source===SalesReturnDocumentItem::SOURCE_EXISTING_PRODUCT){ $variant=ProductVariant::with('product')->findOrFail((int)$row['product_variant_id']); $attrs += ['product_id'=>$variant->product_id,'product_variant_id'=>$variant->id,'product_name_snapshot'=>$variant->product?->name,'variant_name_snapshot'=>$variant->variant_name,'sku_snapshot'=>$variant->variant_code,'barcode_snapshot'=>$variant->variant_code]; } else { $payload=$row['new_product_payload']??[]; $attrs += ['product_name_snapshot'=>$payload['product_name']??null,'variant_name_snapshot'=>$payload['variant_name']??null,'sku_snapshot'=>$payload['sku']??null,'barcode_snapshot'=>$payload['barcode']??null,'purchase_price'=>(int)($payload['purchase_price']??$row['purchase_price']??0),'sell_price'=>(int)($payload['sell_price']??$row['sell_price']??0),'new_product_payload'=>$payload]; } $out[]=$attrs; } return $out; }
    public function resolveDestinationWarehouse(string $condition, int $requestedId=0, bool $canOverride=false): Warehouse { $type=$condition===SalesReturnDocumentItem::CONDITION_HEALTHY?'central':'return'; if($canOverride && $requestedId>0){$w=Warehouse::whereKey($requestedId)->where('is_active',true)->whereIn('type',['central','return'])->first(); if($w)return $w;} return Warehouse::firstOrCreate(['type'=>$type,'name'=>$type==='central'?'انبار مرکزی':'انبار مرجوعی'],['is_active'=>true]); }
    public function materializeNewProduct(SalesReturnDocumentItem $item): void { $p=$item->new_product_payload ?: []; foreach(['product_name','variant_name','sku','category_id'] as $k) if(empty($p[$k])) throw ValidationException::withMessages(["items.$item->sort_order.new_product_payload.$k"=>'اطلاعات کالای جدید ناقص است.']); if(ProductVariant::where('variant_code',$p['sku'])->exists()) throw ValidationException::withMessages(["items.$item->sort_order.new_product_payload.sku"=>'SKU تکراری است.']); $cat=Category::findOrFail((int)$p['category_id']); $product=Product::create(['category_id'=>$cat->id,'name'=>$p['product_name'],'sku'=>'SR-'.uniqid(),'code'=>$p['sku'],'barcode'=>$p['barcode']??null,'stock'=>0,'price'=>(int)($p['sell_price']??0),'is_sellable'=>(bool)($p['sales_enabled']??true),'unit'=>$p['unit']??null]); $variant=ProductVariant::create(['product_id'=>$product->id,'variant_name'=>$p['variant_name'],'variety_name'=>$p['variant_name'],'variety_code'=>'0000','variant_code'=>$p['sku'],'buy_price'=>(int)($p['purchase_price']??0),'sell_price'=>(int)($p['sell_price']??0),'stock'=>0,'reserved'=>0,'is_active'=>true,'sales_enabled'=>(bool)($p['sales_enabled']??true)]); $item->update(['product_id'=>$product->id,'product_variant_id'=>$variant->id,'created_product_id'=>$product->id,'created_variant_id'=>$variant->id]); }
    public function recordInventoryEntry(SalesReturnDocumentItem $item, ?int $actorId): void { if(StockMovement::where('reference_type',SalesReturnDocumentItem::class)->where('reference_id',$item->id)->exists()) return; $before=(int)WarehouseStock::where('warehouse_id',$item->destination_warehouse_id)->where('product_variant_id',$item->product_variant_id)->value('quantity'); WarehouseStockService::change($item->destination_warehouse_id,(int)$item->product_id,(int)$item->return_quantity,(int)$item->product_variant_id); $after=(int)WarehouseStock::where('warehouse_id',$item->destination_warehouse_id)->where('product_variant_id',$item->product_variant_id)->value('quantity'); StockMovement::create(['product_id'=>$item->product_id,'product_variant_id'=>$item->product_variant_id,'warehouse_id'=>$item->destination_warehouse_id,'user_id'=>$actorId ?: 1,'type'=>'in','reason'=>'sales_return','quantity'=>$item->return_quantity,'stock_before'=>$before,'stock_after'=>$after,'note'=>'برگشت از فروش '.$item->document->document_number,'reference'=>$item->document->document_number,'reference_type'=>SalesReturnDocumentItem::class,'reference_id'=>$item->id]); }
    public function recordCustomerCredit(SalesReturnDocument $doc, ?int $actorId): void { if($doc->total_refund_amount<=0)return; CustomerLedger::updateOrCreate(['customer_id'=>$doc->customer_id,'reference_type'=>SalesReturnDocument::class,'reference_id'=>$doc->id,'type'=>'credit'],['amount'=>$doc->total_refund_amount,'note'=>'بستانکاری بابت برگشت از فروش شماره '.$doc->document_number]); }
    private function refreshTotals(SalesReturnDocument $doc): void { $doc->load('items'); $doc->update(['items_count'=>$doc->items->count(),'total_quantity'=>$doc->items->sum('return_quantity'),'total_refund_amount'=>$doc->items->sum('refund_amount')]); }
    private function condition(?string $c): string { return in_array($c,[SalesReturnDocumentItem::CONDITION_HEALTHY,SalesReturnDocumentItem::CONDITION_DAMAGED],true)?$c:SalesReturnDocumentItem::CONDITION_HEALTHY; }
    private function nextDocumentNumber(): string { for($i=0;$i<5;$i++){ try{return DB::transaction(function(){ DB::table('document_sequences')->updateOrInsert(['type'=>'sales_return'],['last_number'=>0,'created_at'=>now(),'updated_at'=>now()]); $seq=DB::table('document_sequences')->where('type','sales_return')->lockForUpdate()->first(); $next=((int)$seq->last_number)+1; DB::table('document_sequences')->where('type','sales_return')->update(['last_number'=>$next,'updated_at'=>now()]); return 'SR-'.str_pad((string)$next,6,'0',STR_PAD_LEFT);}); } catch(QueryException $e){ if($i===4) throw $e; }} throw new \RuntimeException('Cannot generate sales return number.'); }
}
