<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><style>
body{font-family:ariafont,dejavusans,sans-serif;direction:rtl;color:#16354F;font-size:8pt}.product-price-table{width:100%;table-layout:fixed;border-collapse:collapse;border:0.7px solid #C9D7DF;margin-top:1mm;margin-bottom:3mm}.product-price-table thead{display:table-header-group}.product-price-table th,.product-price-table td{border-left:0.6px solid #D7E2E8}.product-price-table th:last-child,.product-price-table td:last-child{border-left:0}.product-header-row th{background:#EDF5F8;border-top:1.2px solid #173A53;border-bottom:0.7px solid #C9D7DF;padding:7px 10px;text-align:right}.product-header-row .product-summary-price{text-align:center;font-size:9px;font-weight:600;color:#2879A8;white-space:nowrap;direction:rtl}.product-title{font-size:10px;font-weight:600;color:#183747;margin-bottom:2px}.product-meta{font-size:7.2px;color:#71828D;line-height:1.55}.product-image{width:38px;height:38px;object-fit:contain;margin-left:6px;vertical-align:middle}.column-header-row th{background:#173A53;color:#fff;font-size:9px;font-weight:600;padding:6px 9px;text-align:center;height:30px;border-left:0.6px solid rgba(255,255,255,0.18);border-bottom:0.7px solid #173A53}.column-header-row th:last-child{border-left:0}.price-list-detail-row td{background:#fff;border-bottom:0.5px solid #E1E9ED;line-height:1.65}.price-list-detail-row:nth-child(even) td{background:#FAFCFD}.price-list-models{font-size:8px;padding:6px 10px 7px 12px;text-align:right;vertical-align:top;direction:rtl;unicode-bidi:plaintext}.price-list-colors{font-size:7.7px;padding:6px 10px 7px 10px;text-align:right;vertical-align:top;direction:rtl}.price-list-price{font-size:8.8px;font-weight:600;padding:6px 8px 7px 8px;text-align:center;vertical-align:top;direction:rtl;white-space:nowrap;color:#16354F}.price-list-price--range{font-size:8.1px}.model-token{display:inline-block;white-space:nowrap;direction:ltr;unicode-bidi:isolate}.color-dot{display:inline-block;width:5px;height:5px;border:0.5px solid #94a3b8;margin-left:3px}.colors-grid{width:100%;table-layout:fixed;border-collapse:collapse;font-size:7.1px;line-height:1.55}.colors-grid--dense{font-size:6.8px}.colors-grid td{width:33.33%;border:0!important;padding:1px 3px!important;text-align:right;background:transparent!important}.product-price-table--small{page-break-inside:avoid}.product-price-table--large{page-break-inside:auto}
</style></head><body>
@foreach($products as $product)
@php $isLarge = count($product['groups']) > 4 || collect($product['groups'])->contains(fn($group) => count($group['colors']) > 24 || count($group['models']) > 25); @endphp
<table class="product-price-table {{ $isLarge ? 'product-price-table--large' : 'product-price-table--small' }}">
<colgroup><col style="width: 46%"><col style="width: 38%"><col style="width: 16%"></colgroup>
<thead><tr class="product-header-row"><th colspan="2"><div>@if($product['has_real_image'])<img class="product-image" src="{{ $product['image_path'] }}" alt="{{ $product['name'] }}">@endif<span class="product-title">{{ $product['name'] }}</span></div><div class="product-meta">دسته: {{ $product['category_name'] }} | {{ $product['model_count'] }} مدل | {{ $product['color_count'] }} رنگ | {{ $product['variant_count'] }} تنوع</div></th><th class="product-summary-price">{{ $product['price_summary'] }}</th></tr><tr class="column-header-row"><th>مدل‌های سازگار</th><th>رنگ‌های قابل سفارش</th><th>قیمت</th></tr></thead>
<tbody>
@foreach($product['groups'] as $group)
<tr class="price-list-detail-row"><td class="price-list-models">@foreach($group['models'] as $model)<span dir="ltr" class="model-token">{{ $model }}</span>{{ $loop->last ? '' : '، ' }}@endforeach</td><td class="price-list-colors">@include('product-exports.partials.color-list', ['colors'=>$group['colors']])</td><td class="price-list-price {{ str_starts_with($group['price_label'], 'از ') ? 'price-list-price--range' : '' }}">{{ $group['price_label'] }}</td></tr>
@endforeach
</tbody></table>
@endforeach
</body></html>
