<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><style>
body{font-family:ariafont,dejavusans,sans-serif;direction:rtl;color:#16354F;font-size:8pt}table{border-collapse:collapse}.price-list-table{width:100%;table-layout:fixed}.price-list-table thead{display:table-header-group}.price-list-table th{background:#16354F;color:#fff;border:1px solid #16354F;padding:5px;font-size:8pt}.price-list-table td{border-bottom:1px solid #D8E3E9;padding:4px 5px;vertical-align:top}.price-list-product-header td{background:#EEF5F8;border-top:1.2px solid #16354F;border-bottom:1px solid #D8E3E9;min-height:42px}.product-image{width:40px;height:40px;object-fit:contain}.product-title{font-size:10.5pt;font-weight:700;color:#16354F}.product-meta{font-size:7.5pt;color:#667784;line-height:1.7}.product-price-summary{font-size:8pt;color:#2879A8;font-weight:700}.price-list-detail-row:nth-child(even) td{background:#FAFCFD}.price-list-models{width:42%;font-size:8pt;line-height:1.7;direction:rtl;unicode-bidi:plaintext}.price-list-colors{width:40%;font-size:7.6pt;line-height:1.5}.price-list-price{width:18%;font-size:8.5pt;font-weight:600;white-space:nowrap;color:#16354F}.ltr{direction:ltr;unicode-bidi:isolate;white-space:nowrap}.color-dot{display:inline-block;width:5px;height:5px;border:0.5px solid #94a3b8;margin-left:3px}.colors-table{width:100%;font-size:7pt;line-height:1.5}.colors-table td{border:0!important;padding:1px 2px!important;background:transparent!important}.small-product{page-break-inside:avoid}.large-product{page-break-inside:auto}
</style></head><body><table class="price-list-table"><thead><tr><th style="width:42%">مدل‌های سازگار</th><th style="width:40%">رنگ‌های قابل سفارش</th><th style="width:18%">قیمت</th></tr></thead>
@foreach($products as $product)
<tbody class="{{ count($product['groups']) <= 4 ? 'small-product' : 'large-product' }}">
<tr class="price-list-product-header"><td colspan="3"><table width="100%"><tr>@if($product['has_real_image'])<td width="46"><img class="product-image" src="{{ $product['image_path'] }}" alt="{{ $product['name'] }}"></td>@endif<td><div class="product-title">{{ $product['name'] }}</div><div class="product-meta">دسته: {{ $product['category_name'] }} | {{ $product['model_count'] }} مدل | {{ $product['color_count'] }} رنگ | {{ $product['variant_count'] }} تنوع</div></td><td width="150" align="left"><div class="product-price-summary">{{ $product['price_summary'] }}</div></td></tr></table></td></tr>
@foreach($product['groups'] as $group)
<tr class="price-list-detail-row"><td class="price-list-models">@foreach($group['models'] as $model)<span class="ltr">{{ $model }}</span>{{ $loop->last ? '' : '، ' }}@endforeach</td><td class="price-list-colors">@include('product-exports.partials.color-list', ['colors'=>$group['colors'], 'columns'=>$group['color_columns']])</td><td class="price-list-price">{{ $group['price_label'] }}</td></tr>
@endforeach
</tbody>
@endforeach
</table></body></html>
