<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>کاتالوگ محصولات</title><link rel="stylesheet" href="{{ asset('css/Vazirmatn.css') }}"><style>
@page{size:A4 portrait;margin:5mm 6mm}*{box-sizing:border-box}body{margin:0;background:#fff;color:#263746;font-family:"Vazirmatn",Vazirmatn,Tahoma,Arial,sans-serif;direction:rtl;text-align:right;font-size:8.3px}.print-shell{width:100%}.toolbar{display:flex;gap:6px;margin:0 0 5px}.toolbar button,.toolbar a{border:1px solid #0b5fa8;background:#0b5fa8;color:#fff;padding:4px 8px;text-decoration:none;font:inherit;cursor:pointer}.toolbar a{background:#fff;color:#0b5fa8}.report-header{height:14mm;display:flex;align-items:center;gap:8px;border-bottom:1px solid #cfe1f0;margin-bottom:4px;padding-bottom:3px}.logo{width:28px;height:28px;display:grid;place-items:center;background:#eef6fc;color:#0b5fa8;font-weight:800;font-size:10px}.report-title{min-width:150px}.report-title h1{margin:0;color:#084a84;font-size:12px}.report-title p{margin:1px 0 0;font-size:7.6px;color:#718096}.print-meta{font-size:7.8px;color:#435568;line-height:1.8}.catalog-print-table{width:100%;border-collapse:collapse;table-layout:fixed}.catalog-print-table col:nth-child(1){width:6%}.catalog-print-table col:nth-child(2){width:10%}.catalog-print-table col:nth-child(3){width:59%}.catalog-print-table col:nth-child(4){width:25%}.catalog-print-table th{background:#eef6fc;border:1px solid #d7e6f2;padding:3px 4px;font-size:7.8px}.catalog-print-table td{border-bottom:1px solid #edf3f8;padding:2px 4px;vertical-align:middle}.catalog-product-group{break-inside:auto;page-break-inside:auto}.catalog-product-row{height:32px;background:#f3f9ff;font-weight:600}.product-name{font-size:8.8px}.catalog-variant-row{height:18px;background:#fff;font-weight:300}.catalog-variant-row td{font-size:7.8px;color:#3f5364;border-bottom:1px solid #f1f5f9}.variant-name{padding-right:8px}.price{direction:ltr;unicode-bidi:isolate;font-variant-numeric:tabular-nums;white-space:nowrap;font-weight:600}.catalog-print-image{width:28px;height:28px;max-width:32px;max-height:32px;object-fit:contain;background:#fff}.placeholder{width:28px;height:28px;display:inline-grid;place-items:center;background:#f8fafc;color:#94a3b8;font-size:7px}.is-broken{display:none}thead{display:table-header-group}a[href]:after{content:""}@media print{.no-print{display:none!important}.report-header{position:static}.catalog-print-table th{-webkit-print-color-adjust:exact;print-color-adjust:exact}.catalog-product-row{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
</style></head><body><div class="print-shell">
<div class="toolbar no-print"><button id="printButton" disabled>آماده‌سازی چاپ...</button><a href="{{ route('admin.product-exports.index', request()->query()) }}">بازگشت</a></div>
<header class="report-header"><div class="logo">آریا</div><div class="report-title"><h1>کاتالوگ محصولات</h1><p>{{ $meta['store_name'] }} | {{ $meta['generated_at'] }}</p></div><div class="print-meta">دسته: {{ $meta['subcategory'] !== 'همه زیردسته‌ها' ? $meta['subcategory'] : $meta['root_category'] }} | نوع مدل: {{ $meta['model_brand'] }} | مدل‌ها: {{ $meta['model_lists'] }} | وضعیت: {{ $meta['stock_status'] }} | تعداد: {{ number_format($products->count()) }}</div></header>
<table class="catalog-print-table"><colgroup><col><col><col><col></colgroup><thead><tr><th>ردیف</th><th>تصویر</th><th>نام محصول یا تنوع</th><th>قیمت</th></tr></thead>
@foreach($products as $row)<tbody class="catalog-product-group"><tr class="catalog-product-row"><td>{{ $loop->iteration }}</td><td><img class="catalog-print-image" src="{{ $row['image_url'] }}" alt="{{ $row['name'] }}" loading="eager" onerror="this.classList.add('is-broken');this.insertAdjacentHTML('afterend','<span class=&quot;placeholder&quot;>ARIA</span>')"></td><td class="product-name">{{ $row['name'] }}</td><td><span class="price">{{ $row['price_label'] }}</span></td></tr>@foreach($row['variants'] as $variant)<tr class="catalog-variant-row"><td></td><td></td><td class="variant-name">↳ {{ $variant['name'] }}</td><td><span class="price">{{ $variant['price_label'] }}</span></td></tr>@endforeach</tbody>@endforeach
</table></div><script>
const button=document.getElementById('printButton');const waitForImages=()=>Promise.all([...document.images].map(img=>img.complete?Promise.resolve():new Promise(resolve=>{img.addEventListener('load',resolve,{once:true});img.addEventListener('error',resolve,{once:true});})));async function prepare(){if(document.fonts?.ready)await document.fonts.ready;await waitForImages();button.disabled=false;button.textContent='چاپ محصولات'}button.addEventListener('click',async()=>{button.disabled=true;button.textContent='آماده‌سازی...';await prepare();window.print();button.disabled=false;button.textContent='چاپ محصولات'});prepare();
</script></body></html>
