<!doctype html>
<html lang="fa" dir="rtl">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>کاتالوگ محصولات</title><link rel="stylesheet" href="{{ asset('css/Vazirmatn.css') }}"><style>
@page{size:A4 portrait;margin:10mm}*{box-sizing:border-box}body{margin:0;background:#f4f7fb;color:#263746;font-family:"Vazirmatn",Vazirmatn,Tahoma,Arial,sans-serif;direction:rtl;text-align:right;font-size:12px}.print-shell{max-width:1100px;margin:0 auto;padding:16px}.report-header{display:flex;justify-content:space-between;gap:16px;align-items:center;border:1px solid #cfe1f0;background:#fff;border-radius:16px;padding:14px;margin-bottom:12px}.logo{width:58px;height:58px;border-radius:14px;background:#eef6fc;display:grid;place-items:center;color:#0b5fa8;font-weight:900}.report-title h1{margin:0;color:#084a84;font-size:22px}.report-title p{margin:4px 0 0;color:#718096}.meta{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-bottom:12px}.meta div{background:#fff;border:1px solid #cfe1f0;border-radius:12px;padding:8px}.meta span{display:block;color:#718096;font-size:10px}.meta strong{display:block;margin-top:3px}.toolbar{display:flex;gap:8px;margin-bottom:12px}.toolbar button,.toolbar a{border:1px solid #0b5fa8;background:#0b5fa8;color:#fff;border-radius:10px;padding:9px 14px;text-decoration:none;font:inherit;cursor:pointer}.toolbar a{background:#fff;color:#0b5fa8}.catalog-product{background:#fff;border:1px solid #cfe1f0;border-radius:14px;margin-bottom:10px;overflow:hidden;break-inside:avoid;page-break-inside:avoid}.product-main{display:grid;grid-template-columns:42px 82px 1fr 150px;gap:10px;align-items:center;padding:10px;border-bottom:1px solid #e5eef6}.product-main img{width:72px;height:72px;object-fit:contain;background:#f8fafc;border:1px solid #cfe1f0;border-radius:12px}.row-no{font-weight:900;color:#0b5fa8}.product-name{font-weight:900;font-size:14px}.category{display:block;color:#718096;margin-top:3px}.price,.variant-price{direction:ltr;unicode-bidi:isolate;font-variant-numeric:tabular-nums;font-weight:900;white-space:nowrap}.variants{padding:4px 96px 8px 14px}.variant{display:flex;justify-content:space-between;gap:12px;padding:6px 0;border-bottom:1px dashed #dbe8f3}.variant:last-child{border-bottom:0}.variant em{font-style:normal;color:#718096;margin-right:5px}a[href]:after{content:""}.is-broken{display:none}.placeholder{width:72px;height:72px;border-radius:12px;background:#eef6fc;display:grid;place-items:center;color:#0b5fa8}@media print{.no-print{display:none!important}body{background:#fff!important}.print-shell{padding:0}.report-header{border-radius:0}.catalog-product{break-inside:avoid;page-break-inside:avoid}thead{display:table-header-group}}@media(max-width:700px){.meta{grid-template-columns:1fr}.product-main{grid-template-columns:32px 72px 1fr}.product-main .price{grid-column:3}.variants{padding:8px 12px}.variant{flex-direction:column}}
</style></head><body><div class="print-shell">
<div class="report-header"><div class="logo">آریا</div><div class="report-title"><h1>کاتالوگ محصولات</h1><p>نسخه چاپی محصولات و تنوع‌ها</p></div><div><strong>{{ $meta['store_name'] }}</strong><br><span>{{ $meta['generated_at'] }}</span></div></div>
<div class="toolbar no-print"><button id="printButton" disabled>آماده‌سازی چاپ...</button><a href="{{ route('admin.product-exports.index', request()->query()) }}">بازگشت</a></div>
<section class="meta"><div><span>دسته اصلی</span><strong>{{ $meta['root_category'] }}</strong></div><div><span>زیردسته</span><strong>{{ $meta['subcategory'] }}</strong></div><div><span>مدل‌ها</span><strong>{{ $meta['model_lists'] }}</strong></div><div><span>وضعیت</span><strong>{{ $meta['stock_status'] }}</strong></div><div><span>تعداد محصولات</span><strong>{{ number_format($products->count()) }}</strong></div></section>
@foreach($products as $row)<article class="catalog-product"><div class="product-main"><div class="row-no">{{ $loop->iteration }}</div><div><img src="{{ $row['image_url'] }}" alt="{{ $row['name'] }}" loading="eager" onerror="this.classList.add('is-broken');this.insertAdjacentHTML('afterend','<span class=&quot;placeholder&quot;>📦</span>')"></div><div><div class="product-name">{{ $row['name'] }}</div><span class="category">{{ $row['category_name'] }}</span></div><div class="price">{{ $row['price_label'] }}</div></div><div class="variants">@forelse($row['variants'] as $variant)<div class="variant"><span>تنوع: {{ $variant['name'] }} <em>{{ $variant['model_list_name'] }}</em></span><strong class="variant-price">{{ $variant['price_label'] }}</strong></div>@empty<div class="variant">بدون تنوع قابل نمایش</div>@endforelse</div></article>@endforeach
</div><script>
const button=document.getElementById('printButton');const waitForImages=()=>Promise.all([...document.images].map(img=>img.complete?Promise.resolve():new Promise(resolve=>{img.addEventListener('load',resolve,{once:true});img.addEventListener('error',resolve,{once:true});})));async function prepare(){if(document.fonts?.ready)await document.fonts.ready;await waitForImages();button.disabled=false;button.textContent='چاپ محصولات'}button.addEventListener('click',async()=>{button.disabled=true;button.textContent='آماده‌سازی...';await prepare();window.print();button.disabled=false;button.textContent='چاپ محصولات'});prepare();
</script></body></html>
