@extends('layouts.app')

@section('content')
<style>
.price-change-shell{max-width:1200px;margin-inline:auto;font-size:.88rem}.pc-card{background:#fff;border:1px solid #e5e7eb;border-radius:14px;box-shadow:0 4px 16px rgba(15,23,42,.04);margin-bottom:16px}.pc-card__head{padding:14px 18px;border-bottom:1px solid #eef2f7;font-weight:700;color:#1f2937}.pc-card__body{padding:18px}.scope-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.summary-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.summary-tile{border:1px solid #eef2f7;border-radius:10px;padding:10px;background:#f9fafb}.preview-table-wrap{max-width:100%;overflow-x:auto}.preview-row-increase{background:#f0fdf4}.preview-row-decrease{background:#fef2f2}.preview-row-same{background:#f9fafb}.preview-row-error{background:#fee2e2}.form-label{font-weight:600;color:#374151}.muted-help{font-size:.78rem;color:#6b7280}.pc-actions{display:flex;gap:10px;justify-content:flex-end}@media(max-width:992px){.scope-grid,.summary-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:576px){.scope-grid,.summary-grid{grid-template-columns:1fr}.pc-actions{flex-direction:column}.pc-actions .btn{width:100%}.price-change-shell{font-size:.84rem}.preview-table-wrap table{min-width:760px}}
</style>
<div class="container-fluid py-4" dir="rtl">
    <div class="price-change-shell">
        <div class="d-flex justify-content-between align-items-start gap-3 mb-4"><div><h1 class="h4 fw-bold text-primary mb-1">ثبت سند تغییر قیمت</h1><p class="text-muted mb-0">انتخاب محدوده به‌صورت زنجیره‌ای انجام می‌شود و قیمت‌ها فقط هنگام اعمال سند تغییر می‌کنند.</p></div><a href="{{ route('products.price-changes.index') }}" class="btn btn-outline-secondary">بازگشت</a></div>
        @if ($errors->any()) <div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div> @endif
        <form id="price-change-form" method="post" action="{{ route('products.price-changes.store') }}">@csrf
            <section class="pc-card"><div class="pc-card__head">۱. اطلاعات سند</div><div class="pc-card__body"><label class="form-label">عنوان سند</label><input name="title" class="form-control" value="{{ old('title') }}" placeholder="افزایش قیمت گاردهای سامسونگ"><label class="form-label mt-3">توضیحات</label><textarea name="note" class="form-control" rows="3" placeholder="اصلاح قیمت بر اساس لیست جدید تأمین‌کننده">{{ old('note') }}</textarea></div></section>
            <section class="pc-card"><div class="pc-card__head">۲. انتخاب محدوده تغییر</div><div class="pc-card__body"><div class="scope-grid">
                <div><label class="form-label">دسته‌بندی اصلی</label><select id="category_id" name="category_id" class="form-select" required><option value="">انتخاب دسته‌بندی اصلی</option>@foreach($rootCategories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div>
                <div><label class="form-label">زیر‌دسته‌بندی</label><select id="subcategory_id" name="subcategory_id" class="form-select" disabled><option value="">همه زیر‌دسته‌ها</option></select><div id="subcategory-empty" class="muted-help mt-1 d-none">این دسته‌بندی زیر‌دسته‌ای ندارد. می‌توانید محصول یا کل دسته را انتخاب کنید.</div></div>
                <div><label class="form-label">محصول</label><select id="product_id" name="product_id" class="form-select" disabled><option value="">همه محصولات این محدوده</option></select><div class="muted-help mt-1">برای جستجو حداقل ۲ حرف تایپ کنید.</div></div>
                <div><label class="form-label">تنوع‌ها</label><select id="variant_ids" name="variant_ids[]" class="form-select" multiple disabled size="5"></select><div class="muted-help mt-1">خالی بودن یعنی همه تنوع‌های محصول.</div></div>
            </div><div class="d-flex flex-wrap gap-3 mt-3 small"><label><input type="checkbox" name="include_active_products_only" value="1" checked> فقط محصولات فعال</label><label><input type="checkbox" name="include_active_variants_only" value="1" checked> فقط تنوع‌های فعال</label><label><input type="checkbox" name="in_stock_only" value="1"> فقط تنوع‌های دارای موجودی</label></div><div id="scope-text" class="alert alert-light border mt-3 mb-0">برای شروع، دسته‌بندی اصلی را انتخاب کنید.</div><div class="summary-grid mt-3"><div class="summary-tile">تعداد محصولات<br><strong id="products-count">—</strong></div><div class="summary-tile">تعداد تنوع‌های مشمول<br><strong id="variants-count">—</strong></div><div class="summary-tile">تنوع‌های فعال<br><strong id="active-count">—</strong></div><div class="summary-tile">نامعتبر/حذف‌شده<br><strong id="invalid-count">—</strong></div></div></div></section>
            <section class="pc-card"><div class="pc-card__head">۳. نوع تغییر قیمت</div><div class="pc-card__body"><div class="row g-3"><div class="col-md-4"><label class="form-label">نوع تغییر</label><select name="change_type" id="change_type" class="form-select">@foreach(\App\Models\PriceChangeDocument::changeTypeLabels() as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">مقدار تغییر <span id="value-unit">درصد</span></label><input name="change_value" id="change_value" type="number" min="0.01" step="0.01" class="form-control" required></div><div class="col-md-4"><label class="form-label">نوع گرد کردن</label><select name="rounding_mode" id="rounding_mode" class="form-select">@foreach(\App\Models\PriceChangeDocument::roundingLabels() as $key=>$label)<option value="{{ $key }}">{{ $label }} ریال</option>@endforeach</select></div></div></div></section>
            <section class="pc-card"><div class="pc-card__head">۴. خلاصه قبل از Preview</div><div class="pc-card__body"><div id="pre-preview-summary" class="alert alert-secondary mb-3">برای مشاهده پیش‌نمایش، دسته‌بندی، نوع تغییر و مقدار را تکمیل کنید.</div><div class="pc-actions"><button type="button" id="preview-btn" class="btn btn-primary" disabled>مشاهده پیش‌نمایش تغییرات</button></div></div></section>
            <section class="pc-card"><div class="pc-card__head">۵. پیش‌نمایش تغییرات</div><div class="pc-card__body"><div id="preview-message" class="text-muted mb-3">هنوز پیش‌نمایش معتبری ساخته نشده است.</div><div id="preview-summary" class="summary-grid mb-3 d-none"></div><div class="preview-table-wrap"><table class="table table-sm align-middle"><thead><tr><th>محصول</th><th>تنوع</th><th>کد / SKU</th><th>قیمت فعلی</th><th>قیمت جدید</th><th>اختلاف</th><th>درصد تغییر</th><th>وضعیت</th></tr></thead><tbody id="preview-body"></tbody></table></div></div><div class="card-footer bg-white pc-actions"><button id="submit-btn" class="btn btn-success" disabled>ثبت پیش‌نویس سند تغییر قیمت</button></div></section>
        </form>
    </div>
</div>
<script>
const form=document.getElementById('price-change-form'),cat=document.getElementById('category_id'),sub=document.getElementById('subcategory_id'),prod=document.getElementById('product_id'),vars=document.getElementById('variant_ids'),previewBtn=document.getElementById('preview-btn'),submitBtn=document.getElementById('submit-btn'),body=document.getElementById('preview-body'),msg=document.getElementById('preview-message');let previewIsValid=false,counts={variants_count:0};const csrf='{{ csrf_token() }}';
function money(n){return Number(n||0).toLocaleString('fa-IR')} function opt(el,v,t){let o=document.createElement('option');o.value=v;o.textContent=t;el.appendChild(o);return o} function invalidate(){previewIsValid=false;submitBtn.disabled=true;body.innerHTML='';msg.textContent='محدوده یا نوع تغییر عوض شده است. پیش‌نمایش را مجدداً اجرا کنید.'}
function scopePayload(){return new FormData(form)} function updateText(){let c=cat.selectedOptions[0]?.text||'',s=sub.value?sub.selectedOptions[0]?.text:'',p=prod.value?prod.selectedOptions[0]?.text:'',vc=[...vars.selectedOptions].length;let txt='برای شروع، دسته‌بندی اصلی را انتخاب کنید.';if(cat.value&&!s&&!p)txt=`محدوده نهایی: تمام محصولات و تنوع‌های دسته‌بندی «${c}» و زیر‌دسته‌های آن`;if(s&&!p)txt=`محدوده نهایی: تمام محصولات و تنوع‌های زیر‌دسته «${s}»`;if(p&&!vc)txt=`محدوده نهایی: تمام تنوع‌های محصول «${p}»`;if(p&&vc)txt=`محدوده نهایی: ${vc} تنوع انتخاب‌شده از محصول «${p}»`;document.getElementById('scope-text').textContent=txt;document.getElementById('pre-preview-summary').textContent=cat.value&&document.getElementById('change_value').value?`${txt} | نوع تغییر: ${document.getElementById('change_type').selectedOptions[0].text} | مقدار: ${document.getElementById('change_value').value} ${document.getElementById('value-unit').textContent} | تعداد تنوع‌ها: ${counts.variants_count||0}`:'برای مشاهده پیش‌نمایش، دسته‌بندی، نوع تغییر و مقدار را تکمیل کنید.';previewBtn.disabled=!(cat.value&&document.getElementById('change_value').value&&(counts.variants_count||0)>0)}
async function refreshCounts(){updateText(); if(!cat.value)return;let res=await fetch('{{ route('products.price-changes.scope-summary') }}',{method:'POST',headers:{'X-CSRF-TOKEN':csrf,'Accept':'application/json'},body:scopePayload()});if(!res.ok){msg.textContent='خطا در محاسبه محدوده';return}counts=await res.json();document.getElementById('products-count').textContent=counts.products_count;document.getElementById('variants-count').textContent=counts.variants_count;document.getElementById('active-count').textContent=counts.active_variants_count;document.getElementById('invalid-count').textContent=counts.invalid_variants_count;if(!counts.variants_count)msg.textContent='هیچ تنوعی در این محدوده پیدا نشد.';updateText()}
cat.addEventListener('change',async()=>{invalidate();sub.innerHTML='<option value="">همه زیر‌دسته‌ها</option>';prod.innerHTML='<option value="">همه محصولات این محدوده</option>';vars.innerHTML='';sub.disabled=prod.disabled=!cat.value;vars.disabled=true;document.getElementById('subcategory-empty').classList.add('d-none');if(cat.value){let r=await fetch(`{{ url('/products/price-changes/categories') }}/${cat.value}/children`),d=await r.json();d.forEach(x=>opt(sub,x.id,x.text));if(!d.length)document.getElementById('subcategory-empty').classList.remove('d-none')}refreshCounts()});
sub.addEventListener('change',()=>{invalidate();prod.innerHTML='<option value="">همه محصولات این محدوده</option>';vars.innerHTML='';vars.disabled=true;refreshCounts()});
let productTimer;prod.addEventListener('focus',()=>searchProducts(''));prod.addEventListener('keyup',()=>{clearTimeout(productTimer);productTimer=setTimeout(()=>searchProducts(prod.value),300)});async function searchProducts(q){if(!cat.value)return;let url=new URL('{{ route('products.price-changes.products.search') }}',location.origin);url.searchParams.set('category_id',cat.value);if(sub.value)url.searchParams.set('subcategory_id',sub.value);url.searchParams.set('q',q);let r=await fetch(url),d=await r.json();prod.innerHTML='<option value="">همه محصولات این محدوده</option>';(d.results||[]).forEach(x=>opt(prod,x.id,`${x.text}${x.code?' — '+x.code:''}`))}
prod.addEventListener('change',async()=>{invalidate();vars.innerHTML='';vars.disabled=!prod.value;if(prod.value){let url=new URL(`{{ url('/products/price-changes/products') }}/${prod.value}/variants`,location.origin);new FormData(form).forEach((v,k)=>url.searchParams.append(k,v));let r=await fetch(url),d=await r.json();d.forEach(x=>opt(vars,x.id,`${x.name} — SKU: ${x.sku||'—'} — ${money(x.sell_price)} ریال${x.is_active?'':' — غیرفعال'}`));if(!d.length)msg.textContent='این محصول تنوع قابل انتخاب ندارد.'}refreshCounts()});
['change_type','change_value','rounding_mode','variant_ids'].forEach(id=>document.getElementById(id).addEventListener('change',()=>{invalidate();refreshCounts()}));form.querySelectorAll('input[type=checkbox]').forEach(el=>el.addEventListener('change',()=>{invalidate();if(prod.value)prod.dispatchEvent(new Event('change'));else refreshCounts()}));document.getElementById('change_type').addEventListener('change',()=>{document.getElementById('value-unit').textContent=document.getElementById('change_type').value.includes('percent')?'درصد':'ریال'});
previewBtn.addEventListener('click',async()=>{submitBtn.disabled=true;body.innerHTML='';msg.textContent='در حال محاسبه...';let res=await fetch('{{ route('products.price-changes.preview') }}',{method:'POST',headers:{'X-CSRF-TOKEN':csrf,'Accept':'application/json'},body:scopePayload()});let data=await res.json();if(!res.ok){msg.textContent=Object.values(data.errors||{}).flat().join('، ')||'خطا در پیش‌نمایش';return}(data.items||[]).forEach(i=>body.insertAdjacentHTML('beforeend',`<tr class="preview-row-${i.error?'error':i.status}"><td>${i.product_name||''}</td><td>${i.variant_name||''}</td><td>${i.sku||''}</td><td>${money(i.old_price)}</td><td>${money(i.new_price)}</td><td>${money(i.difference)}</td><td>${i.difference_percent??'—'}</td><td>${i.error?'<span class="text-danger">'+i.error+'</span>':'<span class="text-success">معتبر</span>'}</td></tr>`));let s=data.summary||{};document.getElementById('preview-summary').classList.remove('d-none');document.getElementById('preview-summary').innerHTML=`<div class="summary-tile">محصولات<br><strong>${s.products_count}</strong></div><div class="summary-tile">تنوع‌ها<br><strong>${s.variants_count}</strong></div><div class="summary-tile">معتبر / خطا<br><strong>${s.valid_count} / ${s.errors_count}</strong></div><div class="summary-tile">جمع جدید<br><strong>${money(s.new_total)}</strong></div>`;msg.textContent=s.large_scope_warning?'این سند روی تعداد زیادی تنوع اعمال می‌شود. لطفاً محدوده و پیش‌نمایش را با دقت بررسی کنید.':(s.variants_count?'پیش‌نمایش معتبر ساخته شد.':'هیچ تنوعی برای تغییر قیمت پیدا نشد.');previewIsValid=!!s.variants_count&&!data.has_errors;submitBtn.disabled=!previewIsValid});
form.addEventListener('submit',e=>{if(!previewIsValid){e.preventDefault();msg.textContent='بدون پیش‌نمایش معتبر امکان ثبت سند وجود ندارد.'}});updateText();
</script>
@endsection
