@extends('layouts.app')

@section('content')
<div class="container py-4" dir="rtl">
    <div class="d-flex justify-content-between mb-4"><div><h1 class="h4 fw-bold text-primary">ثبت سند تغییر قیمت</h1><p class="text-muted mb-0">قبل از ثبت پیش‌نویس، تغییرات را پیش‌نمایش کنید.</p></div><a href="{{ route('products.price-changes.index') }}" class="btn btn-outline-secondary align-self-start">بازگشت</a></div>
    @if ($errors->any()) <div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div> @endif
    <form id="price-change-form" method="post" action="{{ route('products.price-changes.store') }}">@csrf
        <div class="row g-3">
            <div class="col-lg-6"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-white fw-bold">اطلاعات سند</div><div class="card-body"><label class="form-label">عنوان سند</label><input name="title" class="form-control" value="{{ old('title') }}"><label class="form-label mt-3">توضیحات</label><textarea name="note" class="form-control" rows="3">{{ old('note') }}</textarea></div></div></div>
            <div class="col-lg-6"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-white fw-bold">نوع تغییر</div><div class="card-body"><label class="form-label">نوع تغییر</label><select name="change_type" class="form-select">@foreach(\App\Models\PriceChangeDocument::changeTypeLabels() as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select><label class="form-label mt-3">مقدار تغییر</label><input name="change_value" type="number" min="0" step="0.01" class="form-control" required><label class="form-label mt-3">نوع گرد کردن</label><select name="rounding_mode" class="form-select">@foreach(\App\Models\PriceChangeDocument::roundingLabels() as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div></div></div>
            <div class="col-12"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">محدوده تغییر</div><div class="card-body"><div class="row g-3"><div class="col-md-3"><label class="form-label">محدوده</label><select name="scope_type" id="scope_type" class="form-select"><option value="category">دسته‌بندی</option><option value="product">محصول</option><option value="variant">تنوع خاص</option><option value="manual">انتخاب دستی</option></select></div><div class="col-md-9 scope-field" data-scope="category"><label class="form-label">دسته‌بندی</label><select name="category_id" class="form-select"><option value="">انتخاب کنید</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div><div class="col-md-9 scope-field d-none" data-scope="product"><label class="form-label">محصول</label><select name="product_id" class="form-select"><option value="">انتخاب کنید</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }} - {{ $product->sku }}</option>@endforeach</select></div><div class="col-md-9 scope-field d-none" data-scope="variant"><label class="form-label">تنوع</label><select name="variant_id" class="form-select"><option value="">انتخاب کنید</option>@foreach($variants as $variant)<option value="{{ $variant->id }}">{{ $variant->product?->name }} / {{ $variant->variant_name ?: $variant->variety_name ?: 'تنوع اصلی' }} - {{ number_format($variant->sell_price) }}</option>@endforeach</select></div><div class="col-md-9 scope-field d-none" data-scope="manual"><label class="form-label">تنوع‌های دستی</label><select name="variant_ids[]" class="form-select" multiple size="6">@foreach($variants as $variant)<option value="{{ $variant->id }}">{{ $variant->product?->name }} / {{ $variant->variant_name ?: $variant->variety_name ?: 'تنوع اصلی' }} - {{ number_format($variant->sell_price) }}</option>@endforeach</select><div class="form-text">برای انتخاب چند مورد Ctrl/Cmd را نگه دارید.</div></div></div></div></div></div>
            <div class="col-12"><div class="card border-0 shadow-sm"><div class="card-header bg-white d-flex justify-content-between"><span class="fw-bold">پیش‌نمایش</span><button type="button" id="preview-btn" class="btn btn-sm btn-primary">پیش‌نمایش تغییرات</button></div><div class="card-body"><div id="preview-message" class="text-muted mb-3">برای مشاهده اثر تغییر قیمت، پیش‌نمایش را اجرا کنید.</div><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>کالا</th><th>تنوع</th><th>کد</th><th>قیمت فعلی</th><th>قیمت جدید</th><th>اختلاف</th><th>درصد</th><th>وضعیت</th></tr></thead><tbody id="preview-body"></tbody></table></div></div><div class="card-footer bg-white text-end"><button id="submit-btn" class="btn btn-success" disabled>ثبت پیش‌نویس سند</button></div></div></div>
        </div>
    </form>
</div>
<script>
const form = document.getElementById('price-change-form'), scope = document.getElementById('scope_type'), submit = document.getElementById('submit-btn'), body = document.getElementById('preview-body'), msg = document.getElementById('preview-message');
function syncScope(){document.querySelectorAll('.scope-field').forEach(el=>el.classList.toggle('d-none', el.dataset.scope !== scope.value)); submit.disabled = true; body.innerHTML='';}
scope.addEventListener('change', syncScope); syncScope();
document.getElementById('preview-btn').addEventListener('click', async () => { submit.disabled=true; body.innerHTML=''; msg.textContent='در حال محاسبه...'; const res = await fetch('{{ route('products.price-changes.preview') }}', {method:'POST', headers:{'X-CSRF-TOKEN':'{{ csrf_token() }}','Accept':'application/json'}, body:new FormData(form)}); const data = await res.json(); if(!res.ok){msg.textContent=Object.values(data.errors||{}).flat().join('، ') || 'خطا در پیش‌نمایش'; return;} (data.items||[]).forEach(i=>{body.insertAdjacentHTML('beforeend', `<tr><td>${i.product_name||''}</td><td>${i.variant_name||''}</td><td>${i.sku||''}</td><td>${Number(i.old_price).toLocaleString()}</td><td>${Number(i.new_price).toLocaleString()}</td><td>${Number(i.difference).toLocaleString()}</td><td>${i.difference_percent ?? '—'}</td><td>${i.error ? '<span class="text-danger">'+i.error+'</span>' : '<span class="text-success">معتبر</span>'}</td></tr>`)}); msg.textContent = data.count ? `${data.count} آیتم محاسبه شد.` : 'هیچ آیتمی پیدا نشد.'; submit.disabled = !data.count || data.has_errors; });
form.addEventListener('change', () => submit.disabled = true);
</script>
@endsection
