@extends('layouts.app')

@section('content')
@php $isDraft = $document->status === \App\Models\PriceChangeDocument::STATUS_DRAFT; @endphp
<div class="container py-4" dir="rtl">
    <div class="d-flex flex-column flex-md-row justify-content-between gap-3 mb-4"><div><h1 class="h4 fw-bold text-primary">سند تغییر قیمت {{ $document->code }}</h1><p class="text-muted mb-0">جزئیات قیمت قبل و بعد هر تنوع</p></div><div class="d-flex gap-2 align-self-start"><a class="btn btn-outline-secondary" href="{{ route('products.price-changes.index') }}">بازگشت</a>@if($isDraft)<form method="post" action="{{ route('products.price-changes.apply', $document) }}">@csrf<button class="btn btn-success">اعمال سند</button></form><form method="post" action="{{ route('products.price-changes.cancel', $document) }}">@csrf<button class="btn btn-outline-danger">لغو سند</button></form>@endif</div></div>
    @if (session('success')) <div class="alert alert-success">{{ session('success') }}</div> @endif
    @if ($errors->any()) <div class="alert alert-danger">{{ $errors->first() }}</div> @endif
    @if($document->status === 'applied')<div class="alert alert-success">این سند اعمال شده است و قیمت فروش آینده کالاها بر اساس آن تغییر کرده است.</div>@elseif($isDraft)<div class="alert alert-warning">این سند هنوز اعمال نشده و قیمت کالاها تغییر نکرده است.</div>@endif
    <div class="card border-0 shadow-sm mb-4"><div class="card-header bg-white fw-bold">اطلاعات سند</div><div class="card-body"><div class="row g-3"><div class="col-md-3"><span class="text-muted">عنوان:</span> {{ $document->title ?: '—' }}</div><div class="col-md-3"><span class="text-muted">وضعیت:</span> {{ $document->statusLabel() }}</div><div class="col-md-3"><span class="text-muted">محدوده:</span> {{ $document->scopeLabel() }}</div><div class="col-md-3"><span class="text-muted">نوع تغییر:</span> {{ $document->changeTypeLabel() }}</div><div class="col-md-3"><span class="text-muted">مقدار:</span> {{ $document->change_value }}</div><div class="col-md-3"><span class="text-muted">گرد کردن:</span> {{ $document->roundingLabel() }}</div><div class="col-md-3"><span class="text-muted">ثبت‌کننده:</span> {{ $document->createdBy?->name ?: '—' }}</div><div class="col-md-3"><span class="text-muted">تاریخ ثبت:</span> {{ optional($document->created_at)->format('Y-m-d H:i') }}</div><div class="col-md-3"><span class="text-muted">اعمال‌کننده:</span> {{ $document->appliedBy?->name ?: '—' }}</div><div class="col-md-3"><span class="text-muted">تاریخ اعمال:</span> {{ optional($document->applied_at)->format('Y-m-d H:i') ?: '—' }}</div><div class="col-12"><span class="text-muted">توضیح:</span> {{ $document->note ?: '—' }}</div></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">آیتم‌ها</div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>کالا</th><th>تنوع</th><th>کد</th><th>قیمت قبل</th><th>قیمت بعد</th><th>اختلاف</th><th>درصد تغییر</th><th>تاریخ اعمال</th></tr></thead><tbody>@foreach($document->items as $item)@php $diff = $item->new_price - $item->old_price; $percent = $item->old_price > 0 ? round(($diff / $item->old_price) * 100, 2) : null; @endphp<tr><td>{{ $item->product_name_snapshot }}</td><td>{{ $item->variant_name_snapshot }}</td><td>{{ $item->sku_snapshot ?: '—' }}</td><td>{{ number_format($item->old_price) }}</td><td class="fw-bold text-primary">{{ number_format($item->new_price) }}</td><td class="{{ $diff >= 0 ? 'text-success' : 'text-danger' }}">{{ number_format($diff) }}</td><td>{{ $percent === null ? '—' : $percent.'٪' }}</td><td>{{ optional($item->applied_at)->format('Y-m-d H:i') ?: '—' }}</td></tr>@endforeach</tbody></table></div></div>
</div>
@endsection
