@include('sales-returns.partials.flash')
@if(!$centralWarehouse)<div class="alert alert-warning">انبار مرکزی در تنظیمات سیستم تعریف نشده است.</div>@endif
@if(!$returnWarehouse)<div class="alert alert-warning">انبار مرجوعی در تنظیمات سیستم تعریف نشده است.</div>@endif
@php
    $isEdit = isset($document);
    $source = old('source_type', $isEdit ? $document->source_type : \App\Models\SalesReturnDocument::SOURCE_INTERNAL_INVOICE);
    $initialItems = old('items', $isEdit ? $document->items->map(fn($item) => [
        'invoice_item_id'=>$item->invoice_item_id,
        'product_id'=>$item->product_id,
        'product_variant_id'=>$item->product_variant_id,
        'product_name_snapshot'=>$item->product_name_snapshot,
        'variant_name_snapshot'=>$item->variant_name_snapshot,
        'sku_snapshot'=>$item->sku_snapshot,
        'sold_quantity_snapshot'=>$item->sold_quantity_snapshot,
        'previous_returned_quantity_snapshot'=>$item->previous_returned_quantity_snapshot,
        'returnable_quantity'=>max((int)$item->sold_quantity_snapshot - (int)$item->previous_returned_quantity_snapshot, 0),
        'return_quantity'=>$item->return_quantity,
        'item_condition'=>$item->item_condition,
        'destination_warehouse_id'=>$item->destination_warehouse_id,
        'refund_unit_price'=>$item->refund_unit_price,
        'refund_amount'=>$item->refund_amount,
        'purchase_price'=>$item->purchase_price,
        'sell_price'=>$item->sell_price,
        'new_product_payload'=>$item->new_product_payload,
    ])->values()->all() : []);
    $customerLabel = $isEdit && $document->customer ? (trim(($document->customer->first_name ?? '').' '.($document->customer->last_name ?? '')) ?: $document->customer->mobile) : '';
    $invoiceSummary = $isEdit && $document->invoice ? ['id'=>$document->invoice->id,'uuid'=>$document->invoice->uuid,'total'=>$document->invoice->total,'status'=>$document->invoice->status,'created_at'=>optional($document->invoice->created_at)->format('Y-m-d'),'items_count'=>$document->items_count] : null;
@endphp
<style>
.sr-form{direction:rtl;--navy:#1e3a5f;--line:#e2e8f0;--soft:#f8fafc;--muted:#64748b;--green:#147a5c}.sr-card{background:#fff;border:1px solid var(--line);border-radius:14px;margin-bottom:14px}.sr-card-head{padding:13px 16px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:10px;align-items:center}.sr-card-title{font-weight:900;color:var(--navy)}.sr-card-sub{font-size:12px;color:var(--muted)}.sr-card-body{padding:16px}.source-card{border:1px solid var(--line);border-radius:12px;padding:14px;cursor:pointer;background:#fff;height:100%}.source-card.active{border-color:var(--green);background:#f0fdf4}.search-panel{position:relative}.search-results{position:absolute;top:100%;right:0;left:0;background:#fff;border:1px solid var(--line);border-radius:10px;z-index:30;max-height:260px;overflow:auto;box-shadow:0 12px 28px rgba(15,23,42,.12)}.result-item{display:block;width:100%;border:0;background:#fff;text-align:right;padding:10px 12px;border-bottom:1px solid #f1f5f9}.result-item:hover{background:#f8fafc}.invoice-summary{background:#f8fafc;border:1px dashed #cbd5e1;border-radius:12px;padding:12px}.sr-table th{font-size:12px;background:#f8fafc;white-space:nowrap}.sr-table td{vertical-align:middle}.qty-stepper{display:flex;gap:4px}.qty-stepper input{width:78px;text-align:center}.summary-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:8px}.summary-box{background:#f8fafc;border:1px solid var(--line);border-radius:12px;padding:10px}.summary-box small{display:block;color:var(--muted);font-size:11px}.summary-box strong{font-size:15px}.drawer-backdrop{position:fixed;inset:0;background:rgba(15,23,42,.45);z-index:1040;display:none}.drawer{position:fixed;top:0;bottom:0;left:0;width:min(520px,96vw);background:#fff;z-index:1050;transform:translateX(-105%);transition:.2s;overflow:auto}.drawer.open{transform:none}.drawer-backdrop.open{display:block}@media(max-width:991.98px){.summary-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.sr-table thead{display:none}.sr-table tr{display:block;border:1px solid var(--line);border-radius:12px;margin-bottom:10px;padding:8px}.sr-table td{display:flex;justify-content:space-between;border:0!important}.sr-table td:before{content:attr(data-label);font-weight:700;color:#64748b}}
</style>
<div class="sr-form" data-can-override="{{ auth()->user()?->hasPermission('sales_returns.override_destination') ? '1':'0' }}" data-can-create-product="{{ auth()->user()?->hasPermission('sales_returns.create_product') ? '1':'0' }}" data-central-id="{{ $centralWarehouse?->id }}" data-return-id="{{ $returnWarehouse?->id }}" data-initial-items='@json($initialItems)' data-initial-invoice='@json($invoiceSummary)'>
<form method="POST" action="{{ $isEdit ? route('sales-returns.update', $document) : route('sales-returns.store') }}" id="salesReturnForm">
@csrf @if($isEdit) @method('PATCH') @endif
<div id="hiddenItems"></div>
<div class="sr-card"><div class="sr-card-head"><div><div class="sr-card-title">1. نوع برگشت</div><div class="sr-card-sub">نوع سند را انتخاب کنید؛ با تغییر نوع، فاکتور و اقلام قبلی پاک می‌شوند.</div></div></div><div class="sr-card-body"><input type="hidden" name="source_type" id="sourceType" value="{{ $source }}"><div class="row g-3"><div class="col-md-6"><div class="source-card" data-source="internal_invoice"><strong>برگشت داخلی</strong><div class="text-muted small mt-1">فاکتور در همین نرم‌افزار ثبت شده است.</div></div></div><div class="col-md-6"><div class="source-card" data-source="sazeh_hesab"><strong>برگشت سازه‌حساب</strong><div class="text-muted small mt-1">فاکتور در سیستم مالی قبلی ثبت شده است.</div></div></div></div></div></div>
<div class="sr-card"><div class="sr-card-head"><div><div class="sr-card-title">2. اطلاعات مشتری و فاکتور</div><div class="sr-card-sub">جستجوی زنده مشتری، انتخاب فاکتور داخلی یا ورود مشخصات سازه‌حساب.</div></div></div><div class="sr-card-body"><div class="row g-3"><div class="col-lg-4 search-panel"><label class="form-label">مشتری</label><input type="hidden" name="customer_id" id="customerId" value="{{ old('customer_id', $document->customer_id ?? '') }}"><input id="customerSearch" class="form-control" value="{{ $customerLabel }}" placeholder="حداقل ۲ کاراکتر: نام، موبایل یا کد"><div id="customerResults" class="search-results d-none"></div>@error('customer_id')<div class="text-danger small">{{ $message }}</div>@enderror</div><div class="col-lg-4 internal-only"><label class="form-label">فاکتور مشتری</label><select id="invoiceSelect" name="invoice_id" class="form-select" @disabled(!old('customer_id', $document->customer_id ?? null))><option value="{{ old('invoice_id', $document->invoice_id ?? '') }}">{{ $invoiceSummary ? ($invoiceSummary['uuid'].' | '.number_format($invoiceSummary['total']).' ریال') : 'ابتدا مشتری را انتخاب کنید' }}</option></select>@error('invoice_id')<div class="text-danger small">{{ $message }}</div>@enderror</div><div class="col-lg-4 sazeh-only"><label class="form-label">شماره فاکتور سازه‌حساب</label><input name="external_invoice_number" value="{{ old('external_invoice_number', $document->external_invoice_number ?? '') }}" class="form-control">@error('external_invoice_number')<div class="text-danger small">{{ $message }}</div>@enderror</div><div class="col-lg-4 sazeh-only"><label class="form-label">تاریخ فاکتور</label><input type="date" name="external_invoice_date" value="{{ old('external_invoice_date', isset($document) && $document->external_invoice_date ? $document->external_invoice_date->format('Y-m-d') : '') }}" class="form-control"></div><div class="col-lg-4"><label class="form-label">علت برگشت</label><select name="return_reason" id="returnReason" class="form-select"><option value="">انتخاب علت...</option>@foreach($returnReasons as $key=>$label)<option value="{{ $key }}" @selected(old('return_reason',$document->return_reason??'')===$key)>{{ $label }}</option>@endforeach</select></div><div class="col-12 internal-only"><div class="invoice-summary" id="invoiceSummaryBox"><strong>خلاصه فاکتور:</strong> <span id="invoiceSummaryText">{{ $invoiceSummary ? ('شماره '.$invoiceSummary['uuid'].' | مبلغ '.number_format($invoiceSummary['total']).' ریال | تعداد اقلام '.$invoiceSummary['items_count']) : 'هنوز فاکتوری انتخاب نشده است.' }}</span></div></div></div></div></div>
<div class="sr-card"><div class="sr-card-head"><div><div class="sr-card-title">4. اقلام برگشتی</div><div class="sr-card-sub internal-only">پس از انتخاب فاکتور، اقلام به صورت خودکار Load می‌شوند. مقدار صفر ذخیره نمی‌شود.</div><div class="sr-card-sub sazeh-only">کالای موجود را جستجو کنید یا Payload کالای جدید بسازید.</div></div><button type="button" class="btn btn-sm btn-outline-primary sazeh-only" id="addSazehRow">افزودن ردیف</button></div><div class="sr-card-body"><div id="itemsError" class="alert alert-warning d-none"></div><div class="table-responsive"><table class="table sr-table" id="itemsTable"><thead id="itemsHead"></thead><tbody id="itemsBody"></tbody></table></div></div></div>
<div class="sr-card"><div class="sr-card-head"><div><div class="sr-card-title">5. خلاصه مالی</div><div class="sr-card-sub">Backend هنگام ذخیره دوباره همه اعداد را محاسبه می‌کند.</div></div></div><div class="sr-card-body"><div class="summary-grid"><div class="summary-box"><small>تعداد اقلام</small><strong id="sumRows">0</strong></div><div class="summary-box"><small>تعداد کل</small><strong id="sumQty">0</strong></div><div class="summary-box"><small>سالم</small><strong id="sumHealthy">0</strong></div><div class="summary-box"><small>معیوب</small><strong id="sumDamaged">0</strong></div><div class="summary-box"><small>مبلغ بستانکاری</small><strong id="sumAmount">0</strong></div><div class="summary-box"><small>انبارهای مقصد</small><strong id="sumWarehouses">—</strong></div></div></div></div>
<div class="sr-card"><div class="sr-card-head"><div><div class="sr-card-title">6. توضیحات</div></div></div><div class="sr-card-body"><textarea name="description" class="form-control" rows="3" placeholder="توضیحات اختیاری یا علت سایر...">{{ old('description',$document->description??'') }}</textarea><div class="alert alert-info mt-3 mb-0">ذخیره پیش‌نویس هیچ تغییری در موجودی و حساب مشتری ایجاد نمی‌کند.</div></div></div>
<div class="d-flex gap-2 justify-content-end mb-4"><button class="btn btn-success">ذخیره پیش‌نویس</button><button type="button" class="btn btn-outline-warning" id="resetFormBtn">پاک‌کردن فرم</button><a class="btn btn-outline-secondary" href="{{ route('sales-returns.index') }}">بازگشت</a></div>
</form>
<div class="drawer-backdrop" id="drawerBackdrop"></div><div class="drawer" id="newProductDrawer"><div class="p-3 border-bottom d-flex justify-content-between"><strong>تعریف کالای جدید سازه‌حساب</strong><button class="btn-close" type="button" id="closeDrawer"></button></div><div class="p-3"><div class="alert alert-info">این کالا تا زمان ثبت نهایی سند در فهرست کالاها ایجاد نمی‌شود.</div><input type="hidden" id="drawerRow"><div class="row g-2"><div class="col-md-6"><input id="npProductName" class="form-control" placeholder="نام محصول"></div><div class="col-md-6"><input id="npVariantName" class="form-control" placeholder="نام تنوع"></div><div class="col-md-6"><input id="npCategory" class="form-control" placeholder="شناسه دسته‌بندی اصلی"></div><div class="col-md-6"><input id="npSubcategory" class="form-control" placeholder="شناسه زیر‌دسته"></div><div class="col-md-6"><input id="npModelList" class="form-control" placeholder="شناسه مدل لیست"></div><div class="col-md-6"><input id="npSku" class="form-control" placeholder="SKU"></div><div class="col-md-6"><input id="npBarcode" class="form-control" placeholder="بارکد"></div><div class="col-md-6"><input id="npUnit" class="form-control" placeholder="واحد"></div><div class="col-md-6"><input id="npPurchase" type="number" class="form-control" placeholder="قیمت خرید"></div><div class="col-md-6"><input id="npSell" type="number" class="form-control" placeholder="قیمت فروش"></div><div class="col-md-6"><select id="npSalesEnabled" class="form-select"><option value="1">قابل فروش</option><option value="0">غیرفعال فروش</option></select></div><div class="col-12"><textarea id="npNote" class="form-control" placeholder="توضیح اختیاری"></textarea></div></div><button type="button" class="btn btn-success w-100 mt-3" id="savePayloadBtn">ثبت Payload در ردیف</button></div></div>
</div>
<script>
(function(){
 const root=document.querySelector('.sr-form'), form=document.getElementById('salesReturnForm'), sourceInput=document.getElementById('sourceType'), body=document.getElementById('itemsBody'), head=document.getElementById('itemsHead'), hidden=document.getElementById('hiddenItems');
 const centralId=root.dataset.centralId, returnId=root.dataset.returnId, canOverride=root.dataset.canOverride==='1', canCreateProduct=root.dataset.canCreateProduct==='1';
 let state={source:sourceInput.value, items:JSON.parse(root.dataset.initialItems||'[]'), invoice:JSON.parse(root.dataset.initialInvoice||'null'), customerId:document.getElementById('customerId').value||null}; let customerAbort=null, invoiceAbort=null, itemAbort=null, productAbort=null;
 const fmt=n=>Number(n||0).toLocaleString('fa-IR'); const defaultWarehouse=c=>c==='damaged'?returnId:centralId;
 function setSource(src,clear=true){state.source=src;sourceInput.value=src;document.querySelectorAll('.source-card').forEach(c=>c.classList.toggle('active',c.dataset.source===src));document.querySelectorAll('.internal-only').forEach(e=>e.style.display=src==='internal_invoice'?'':'none');document.querySelectorAll('.sazeh-only').forEach(e=>e.style.display=src==='sazeh_hesab'?'':'none'); if(clear){state.items=[];state.invoice=null;document.getElementById('invoiceSelect').innerHTML='<option value="">ابتدا مشتری را انتخاب کنید</option>';document.getElementById('invoiceSummaryText').textContent='هنوز فاکتوری انتخاب نشده است.';} render();}
 async function fetchJson(url,ctrlName){ const ctrl=new AbortController(); if(ctrlName==='customer'&&customerAbort) customerAbort.abort(); if(ctrlName==='invoice'&&invoiceAbort) invoiceAbort.abort(); if(ctrlName==='item'&&itemAbort) itemAbort.abort(); if(ctrlName==='product'&&productAbort) productAbort.abort(); if(ctrlName==='customer') customerAbort=ctrl; if(ctrlName==='invoice') invoiceAbort=ctrl; if(ctrlName==='item') itemAbort=ctrl; if(ctrlName==='product') productAbort=ctrl; const r=await fetch(url,{signal:ctrl.signal,headers:{'Accept':'application/json'}}); if(!r.ok) throw new Error('request failed'); return await r.json(); }
 function render(){ renderHead(); renderRows(); renderHidden(); renderSummary(); }
 function renderHead(){ head.innerHTML=state.source==='internal_invoice'?'<tr><th>کالا / تنوع</th><th>کد / SKU</th><th>فروخته</th><th>قبلاً برگشتی</th><th>قابل برگشت</th><th>تعداد</th><th>وضعیت</th><th>انبار مقصد</th><th>مبلغ واحد</th><th>مبلغ کل</th></tr>':'<tr><th>نوع کالا</th><th>کالا / تنوع</th><th>تعداد</th><th>وضعیت</th><th>انبار مقصد</th><th>قیمت خرید</th><th>قیمت فروش</th><th>بستانکاری واحد</th><th>جمع</th><th>حذف</th></tr>'; }
 function renderRows(){ if(state.items.length===0){body.innerHTML='<tr><td colspan="10" class="text-center text-muted py-4">هنوز ردیفی انتخاب نشده است.</td></tr>';return;} body.innerHTML=state.items.map((it,i)=>state.source==='internal_invoice'?internalRow(it,i):sazehRow(it,i)).join(''); }
 function whSelect(it,i){ const val=it.destination_warehouse_id||defaultWarehouse(it.item_condition); const disabled=canOverride?'':'disabled'; return `<select class="form-select form-select-sm js-condition-destination" data-i="${i}" ${disabled}><option value="${centralId}" ${String(val)===String(centralId)?'selected':''}>انبار مرکزی</option><option value="${returnId}" ${String(val)===String(returnId)?'selected':''}>انبار مرجوعی</option></select>`; }
 function conditionSelect(it,i){return `<select class="form-select form-select-sm js-condition" data-i="${i}"><option value="healthy" ${it.item_condition==='healthy'?'selected':''}>سالم</option><option value="damaged" ${it.item_condition==='damaged'?'selected':''}>معیوب</option></select>`;}
 function stepper(it,i,max){return `<div class="qty-stepper"><button type="button" class="btn btn-sm btn-outline-secondary js-dec" data-i="${i}">−</button><input type="number" min="0" max="${max}" class="form-control form-control-sm js-qty" data-i="${i}" value="${it.return_quantity||0}"><button type="button" class="btn btn-sm btn-outline-secondary js-inc" data-i="${i}">+</button></div>`;}
 function internalRow(it,i){ const max=Number(it.returnable_quantity??Math.max((it.sold_quantity_snapshot||0)-(it.previous_returned_quantity_snapshot||0),0)); return `<tr><td data-label="کالا">${it.product_name||it.product_name_snapshot||'—'}<div class="text-muted small">${it.variant_name||it.variant_name_snapshot||''}</div></td><td data-label="کد">${it.sku||it.sku_snapshot||'—'}</td><td data-label="فروخته">${fmt(it.sold_quantity||it.sold_quantity_snapshot)}</td><td data-label="قبلاً برگشتی">${fmt(it.previously_returned_quantity||it.previous_returned_quantity_snapshot)}</td><td data-label="قابل برگشت">${fmt(max)}</td><td data-label="تعداد">${stepper(it,i,max)}</td><td data-label="وضعیت">${conditionSelect(it,i)}</td><td data-label="مقصد">${whSelect(it,i)}</td><td data-label="مبلغ واحد">${fmt(it.refund_unit_price||0)}</td><td data-label="جمع">${fmt(it.refund_amount||0)}</td></tr>`; }
 function sazehRow(it,i){ const payload=it.new_product_payload||{}; const name=it.product_name_snapshot||payload.product_name||'—'; return `<tr><td data-label="نوع"><select class="form-select form-select-sm js-kind" data-i="${i}"><option value="existing" ${!it.new_product_payload?'selected':''}>کالای موجود</option><option value="new" ${it.new_product_payload?'selected':''}>کالای جدید</option></select></td><td data-label="کالا"><div class="input-group input-group-sm"><input class="form-control js-product-search" data-i="${i}" value="${name}" placeholder="جستجوی نام/SKU/بارکد"><button type="button" class="btn btn-outline-secondary js-payload" data-i="${i}" ${canCreateProduct?'':'disabled'}>Payload</button></div><div class="small text-muted">${it.variant_name_snapshot||payload.variant_name||''}</div></td><td data-label="تعداد"><input type="number" min="0" class="form-control form-control-sm js-qty" data-i="${i}" value="${it.return_quantity||0}"></td><td data-label="وضعیت">${conditionSelect(it,i)}</td><td data-label="مقصد">${whSelect(it,i)}</td><td data-label="خرید"><input type="number" class="form-control form-control-sm js-purchase" data-i="${i}" value="${it.purchase_price||payload.purchase_price||''}" ${it.new_product_payload?'':'readonly'}></td><td data-label="فروش"><input type="number" class="form-control form-control-sm js-sell" data-i="${i}" value="${it.sell_price||payload.sell_price||''}" ${it.new_product_payload?'':'readonly'}></td><td data-label="بستانکاری"><input type="number" min="0" class="form-control form-control-sm js-refund-unit" data-i="${i}" value="${it.refund_unit_price||0}"></td><td data-label="جمع">${fmt((it.return_quantity||0)*(it.refund_unit_price||0))}</td><td data-label="حذف"><button type="button" class="btn btn-sm btn-outline-danger js-remove" data-i="${i}">حذف</button></td></tr>`; }
 function renderHidden(){ hidden.innerHTML=state.items.map((it,i)=>{ const fields=[]; const push=(k,v)=>{ if(v!==undefined&&v!==null) fields.push(`<input type="hidden" name="items[${i}][${k}]" value="${String(v).replaceAll('"','&quot;')}">`);}; push('invoice_item_id',it.invoice_item_id); push('product_id',it.product_id); push('product_variant_id',it.product_variant_id); push('return_quantity',it.return_quantity||0); push('item_condition',it.item_condition||'healthy'); push('destination_warehouse_id',it.destination_warehouse_id||defaultWarehouse(it.item_condition)); push('refund_unit_price',it.refund_unit_price||0); if(it.new_product_payload){ Object.entries(it.new_product_payload).forEach(([k,v])=>push(`new_product_payload][${k}`,v)); } return fields.join(''); }).join(''); }
 function renderSummary(){ const chosen=state.items.filter(i=>Number(i.return_quantity)>0), qty=chosen.reduce((s,i)=>s+Number(i.return_quantity||0),0), healthy=chosen.filter(i=>(i.item_condition||'healthy')==='healthy').reduce((s,i)=>s+Number(i.return_quantity||0),0), damaged=qty-healthy, amount=chosen.reduce((s,i)=>s+Number(i.refund_amount||((i.return_quantity||0)*(i.refund_unit_price||0))),0); document.getElementById('sumRows').textContent=fmt(chosen.length);document.getElementById('sumQty').textContent=fmt(qty);document.getElementById('sumHealthy').textContent=fmt(healthy);document.getElementById('sumDamaged').textContent=fmt(damaged);document.getElementById('sumAmount').textContent=fmt(amount)+' ریال';document.getElementById('sumWarehouses').textContent=[...new Set(chosen.map(i=>String(i.destination_warehouse_id||defaultWarehouse(i.item_condition))===String(returnId)?'انبار مرجوعی':'انبار مرکزی'))].join('، ')||'—'; }
 async function loadInvoices(){ const cid=document.getElementById('customerId').value, sel=document.getElementById('invoiceSelect'); if(!cid)return; sel.disabled=true; sel.innerHTML='<option>در حال بارگذاری...</option>'; try{ const j=await fetchJson(`{{ url('/sales-returns/customers') }}/${cid}/invoices`,'invoice'); sel.innerHTML='<option value="">انتخاب فاکتور...</option>'+(j.data||[]).map(x=>`<option value="${x.id}">${x.uuid} | ${fmt(x.total)} ریال | ${x.items_count} قلم | ${x.status_label}</option>`).join(''); sel.disabled=false; }catch(e){ sel.innerHTML='<option>خطا در دریافت فاکتورها</option>'; }}
 async function loadItems(invoiceId){ if(!invoiceId)return; body.innerHTML='<tr><td colspan="10" class="text-center py-4">در حال بارگذاری اقلام...</td></tr>'; try{ const j=await fetchJson(`{{ url('/sales-returns/invoices') }}/${invoiceId}/items`,'item'); state.items=(j.data||[]).map(x=>({invoice_item_id:x.invoice_item_id,product_id:x.product_id,product_variant_id:x.variant_id,product_name_snapshot:x.product_name,variant_name_snapshot:x.variant_name,sku_snapshot:x.sku,sold_quantity_snapshot:x.sold_quantity,previous_returned_quantity_snapshot:x.previously_returned_quantity,returnable_quantity:x.returnable_quantity,return_quantity:0,item_condition:'healthy',destination_warehouse_id:centralId,refund_unit_price:0,refund_amount:0})); document.getElementById('invoiceSummaryText').textContent='فاکتور انتخاب شد؛ اقلام قابل برگشت در جدول نمایش داده شدند.'; render(); }catch(e){document.getElementById('itemsError').textContent='خطا در دریافت اقلام فاکتور.';document.getElementById('itemsError').classList.remove('d-none');}}
 document.addEventListener('click',e=>{ const t=e.target; if(t.closest('.source-card')) setSource(t.closest('.source-card').dataset.source,true); if(t.classList.contains('js-inc')){const i=t.dataset.i,max=Number(state.items[i].returnable_quantity||999999);state.items[i].return_quantity=Math.min(Number(state.items[i].return_quantity||0)+1,max);render();} if(t.classList.contains('js-dec')){const i=t.dataset.i;state.items[i].return_quantity=Math.max(Number(state.items[i].return_quantity||0)-1,0);render();} if(t.id==='addSazehRow'){state.items.push({return_quantity:1,item_condition:'healthy',destination_warehouse_id:centralId,refund_unit_price:0});render();} if(t.classList.contains('js-remove')){state.items.splice(t.dataset.i,1);render();} if(t.classList.contains('js-payload')) openDrawer(t.dataset.i); if(t.id==='resetFormBtn'){if(confirm('فرم پاک شود؟')){state.items=[];state.invoice=null;render();}} });
 document.addEventListener('input',e=>{ const i=e.target.dataset.i; if(i===undefined)return; if(e.target.classList.contains('js-qty')) state.items[i].return_quantity=Math.min(Math.max(Number(e.target.value||0),0),Number(state.items[i].returnable_quantity||999999)); if(e.target.classList.contains('js-refund-unit')) state.items[i].refund_unit_price=Number(e.target.value||0); if(e.target.classList.contains('js-purchase')) state.items[i].purchase_price=Number(e.target.value||0); if(e.target.classList.contains('js-sell')) state.items[i].sell_price=Number(e.target.value||0); renderHidden(); renderSummary(); });
 document.addEventListener('change',e=>{ const i=e.target.dataset.i; if(i===undefined)return; if(e.target.classList.contains('js-condition')){state.items[i].item_condition=e.target.value; if(!canOverride) state.items[i].destination_warehouse_id=defaultWarehouse(e.target.value); if(state.items[i].new_product_payload) state.items[i].new_product_payload.sales_enabled=e.target.value==='healthy'?1:0; render();} if(e.target.classList.contains('js-condition-destination')){state.items[i].destination_warehouse_id=e.target.value;renderHidden();renderSummary();} if(e.target.classList.contains('js-kind')){ if(e.target.value==='new') openDrawer(i); else {delete state.items[i].new_product_payload; render();}} });
 document.getElementById('invoiceSelect')?.addEventListener('change',e=>loadItems(e.target.value));
 const cs=document.getElementById('customerSearch'), cr=document.getElementById('customerResults'); let timer; cs.addEventListener('input',()=>{clearTimeout(timer); timer=setTimeout(async()=>{ if(cs.value.length<2){cr.classList.add('d-none');return;} cr.classList.remove('d-none'); cr.innerHTML='<div class="p-2 text-muted">در حال جستجو...</div>'; try{ const j=await fetchJson(`{{ route('sales-returns.customers.search') }}?q=${encodeURIComponent(cs.value)}`,'customer'); cr.innerHTML=(j.data||[]).map(x=>`<button type="button" class="result-item" data-id="${x.id}" data-text="${x.text}">${x.text}<div class="small text-muted">${x.mobile||''} ${x.code||''}</div></button>`).join('')||'<div class="p-2 text-muted">نتیجه‌ای یافت نشد.</div>'; }catch(e){cr.innerHTML='<div class="p-2 text-danger">خطا در جستجو</div>'; }},300);}); cr.addEventListener('click',e=>{const b=e.target.closest('button'); if(!b)return; document.getElementById('customerId').value=b.dataset.id; cs.value=b.dataset.text; cr.classList.add('d-none'); state.items=[]; loadInvoices(); render();});
 function openDrawer(i){ if(!canCreateProduct)return; document.getElementById('drawerRow').value=i; const p=state.items[i].new_product_payload||{}; ['ProductName','VariantName','Category','Subcategory','ModelList','Sku','Barcode','Unit','Purchase','Sell','Note'].forEach(k=>{const el=document.getElementById('np'+k); if(el) el.value=p[k.charAt(0).toLowerCase()+k.slice(1)]||'';}); document.getElementById('npSalesEnabled').value=p.sales_enabled??(state.items[i].item_condition==='damaged'?0:1); document.getElementById('drawerBackdrop').classList.add('open'); document.getElementById('newProductDrawer').classList.add('open'); }
 function closeDrawer(){document.getElementById('drawerBackdrop').classList.remove('open');document.getElementById('newProductDrawer').classList.remove('open');}
 document.getElementById('closeDrawer').onclick=closeDrawer; document.getElementById('drawerBackdrop').onclick=closeDrawer; document.getElementById('savePayloadBtn').onclick=()=>{ const i=document.getElementById('drawerRow').value; state.items[i].new_product_payload={product_name:npProductName.value,variant_name:npVariantName.value,category_id:npCategory.value,subcategory_id:npSubcategory.value,model_list_id:npModelList.value,sku:npSku.value,barcode:npBarcode.value,unit:npUnit.value,purchase_price:npPurchase.value,sell_price:npSell.value,sales_enabled:npSalesEnabled.value,note:npNote.value}; state.items[i].product_id=null; state.items[i].product_variant_id=null; state.items[i].product_name_snapshot=npProductName.value; state.items[i].variant_name_snapshot=npVariantName.value; state.items[i].purchase_price=npPurchase.value; state.items[i].sell_price=npSell.value; closeDrawer(); render(); };
 setSource(state.source,false); render();
})();
</script>
