<!doctype html>
<html lang="fa" dir="rtl"><head><meta charset="utf-8"><title>{{ $document->document_number }}</title>
<style>@page{size:A4;margin:14mm}body{font-family:Tahoma,Arial,sans-serif;color:#111;font-size:12px}h1{text-align:center}.meta,.totals{display:grid;grid-template-columns:repeat(2,1fr);gap:6px;margin:15px 0}table{width:100%;border-collapse:collapse;margin-bottom:14px}th,td{border:1px solid #777;padding:6px;text-align:right}thead{display:table-header-group}.draft{border:2px solid #a16207;color:#854d0e;padding:8px;text-align:center;font-weight:bold;margin:10px 0}@media print{button{display:none}}</style></head>
<body><button onclick="print()">چاپ</button><h1>سند پورسانت فروشنده</h1>
@if($document->status !== \App\Models\CommissionDocument::STATUS_FINALIZED)<div class="draft">پیش‌نویس — پرداخت نهایی ثبت نشده است</div>@endif
<div class="meta"><div>شماره سند: <b>{{ $document->document_number }}</b></div><div>فروشنده: {{ $document->seller->name }}</div><div>دوره: {{ $document->period->label }}</div><div>وضعیت: {{ $document->status === \App\Models\CommissionDocument::STATUS_FINALIZED ? 'نهایی‌شده' : 'پیش‌نویس' }}</div>@if($document->finalized_at)<div>نهایی‌کننده: {{ $document->finalizer?->name }}</div><div>زمان نهایی‌سازی: {{ \App\Support\JalaliDate::dateTime($document->finalized_at) }}</div>@endif</div>
<h2>فاکتورهای تأییدشده</h2><table><thead><tr><th>فاکتور</th><th>تاریخ</th><th>مشتری</th><th>فروش خالص</th><th>پایه</th><th>کمپین</th><th>پورسانت</th></tr></thead><tbody>@forelse($document->items->where('status','approved') as $item)<tr><td>{{ $item->invoice_number_snapshot }}</td><td>{{ \App\Support\JalaliDate::date($item->invoice_date_snapshot) }}</td><td>{{ $item->customer_name_snapshot }}</td><td>{{ \App\Support\Currency::formatToman($item->net_sales_snapshot) }}</td><td>{{ \App\Support\Currency::formatToman($item->base_commission_snapshot) }}</td><td>{{ \App\Support\Currency::formatToman($item->campaign_commission_snapshot) }}</td><td>{{ \App\Support\Currency::formatToman($item->total_commission_snapshot) }}</td></tr>@empty<tr><td colspan="7">موردی نیست.</td></tr>@endforelse</tbody></table>
<h2>برگشتی‌ها و اصلاحات سیستمی</h2><table><thead><tr><th>شرح</th><th>فاکتور</th><th>مبلغ</th><th>وضعیت</th></tr></thead><tbody>@forelse($document->corrections as $row)<tr><td>{{ $row->description }}</td><td>{{ $row->source_invoice_number }}</td><td>{{ \App\Support\Currency::formatToman($row->total_amount) }}</td><td>{{ ['pending'=>'در انتظار','approved'=>'تأییدشده','rejected'=>'ردشده'][$row->status] ?? $row->status }}</td></tr>@empty<tr><td colspan="4">موردی نیست.</td></tr>@endforelse</tbody></table>
<h2>تعدیلات دستی</h2><table><thead><tr><th>نوع</th><th>شرح</th><th>مبلغ</th><th>وضعیت</th></tr></thead><tbody>@forelse($document->adjustments as $row)<tr><td>{{ ['manual'=>'دستی','carry_forward'=>'انتقال مانده'][$row->type_snapshot] ?? 'تعدیل' }}</td><td>{{ $row->reason_snapshot }}</td><td>{{ \App\Support\Currency::formatToman($row->amount_snapshot) }}</td><td>{{ ['pending'=>'در انتظار','approved'=>'تأییدشده','rejected'=>'ردشده'][$row->status] ?? $row->status }}</td></tr>@empty<tr><td colspan="4">موردی نیست.</td></tr>@endforelse</tbody></table>
<div class="totals"><div>فروش خالص: {{ \App\Support\Currency::formatToman($document->final_net_sales ?? $totals['approved_net_sales']) }}</div><div>پایه: {{ \App\Support\Currency::formatToman($document->final_base_commission ?? $totals['approved_base_commission']) }}</div><div>کمپین: {{ \App\Support\Currency::formatToman($document->final_campaign_commission ?? $totals['approved_campaign_commission']) }}</div><div>اصلاحات: {{ \App\Support\Currency::formatToman($document->final_correction_amount ?? $totals['approved_correction']) }}</div><div>تعدیلات: {{ \App\Support\Currency::formatToman($document->final_adjustment_amount ?? $totals['approved_adjustment']) }}</div><div><b>خالص نهایی: {{ \App\Support\Currency::formatToman($document->final_commission_total ?? $totals['approved_net_total']) }}</b></div></div>
<div>یادداشت: {!! nl2br(e($document->notes ?: '—')) !!}</div></body></html>
