@extends('layouts.app')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><h4 class="mb-0">عملیات گروهی وضعیت فروش</h4><a class="btn btn-outline-secondary" href="{{ route('product-deactivation-documents.create') }}">بازگشت</a></div>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form id="bulkForm" method="POST" action="{{ route('product-deactivation-documents.bulk.store') }}" class="card">
@csrf <input type="hidden" name="preview_token" id="previewToken"><input type="hidden" name="confirmed" value="1">
<div class="card-body">
    <div class="row g-3">
        <div class="col-lg-6"><label class="form-label fw-bold">محدوده</label><div class="d-flex gap-3 flex-wrap"><label><input type="radio" name="scope_type" value="category" checked> دسته‌بندی</label><label><input type="radio" name="scope_type" value="subcategory"> زیردسته</label><label><input type="radio" name="scope_type" value="multiple_products"> چند کالا</label></div></div>
        <div class="col-lg-6"><label class="form-label fw-bold">عملیات</label><div class="d-flex gap-3"><label><input type="radio" name="action_type" value="deactivate" checked> غیرفعال‌سازی</label><label><input type="radio" name="action_type" value="activate"> فعال‌سازی</label></div></div>
        <div class="col-md-6" id="categoryField"><label class="form-label">دسته‌بندی</label><select name="category_id" id="categoryId" class="form-select"><option value="">انتخاب کنید</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div>
        <div class="col-md-6 d-none" id="subcategoryField"><label class="form-label">زیردسته</label><select name="subcategory_id" id="subcategoryId" class="form-select"><option value="">ابتدا دسته را انتخاب کنید</option></select></div>
        <div class="col-12 d-none" id="productsField"><label class="form-label">جستجو و انتخاب چند کالا</label><input id="productSearch" class="form-control" autocomplete="off" placeholder="نام یا کد کالا"><div id="searchResults" class="list-group mt-1"></div><div id="selectedProducts" class="d-flex flex-wrap gap-2 mt-2"></div></div>
        <div class="col-md-6"><label class="form-label">دلیل تغییر وضعیت</label><select name="reason_type" id="reasonType" class="form-select" required></select></div>
        <div class="col-md-6"><label class="form-label">توضیح تکمیلی</label><textarea name="reason_text" class="form-control" rows="2"></textarea><div class="form-text">برای دلیل سفارشی الزامی است.</div></div>
    </div>
    <div id="previewBox" class="border rounded p-3 mt-3 d-none"><div class="fw-bold mb-2">پیش‌نمایش عملیات</div><div id="previewSummary" class="row g-2"></div><div id="previewWarning" class="alert alert-warning py-2 mt-3 mb-2"></div><div id="previewSample" class="small text-muted"></div></div>
</div>
<div class="card-footer bg-white d-flex gap-2"><button type="button" id="previewButton" class="btn btn-outline-primary">مشاهده پیش‌نمایش</button><button id="executeButton" class="btn btn-danger" disabled>تأیید و اجرای عملیات</button></div>
</form>
<script>
const routes={preview:@json(route('product-deactivation-documents.bulk.preview')),search:@json(route('product-deactivation-documents.products.search')),children:@json(url('/product-deactivation-documents/bulk/categories'))};
const reasons={deactivate:@json(\App\Models\ProductDeactivationDocument::reasonLabels()),activate:@json(\App\Models\ProductDeactivationDocument::activationReasonLabels())};
const form=document.getElementById('bulkForm'), selected=new Map(); let timer,aborter;
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function action(){return document.querySelector('[name=action_type]:checked').value} function scope(){return document.querySelector('[name=scope_type]:checked').value}
function reasonsRender(){$('reasonType').innerHTML=Object.entries(reasons[action()]).map(([v,l])=>`<option value="${v}">${esc(l)}</option>`).join('')}
function invalidate(){$('previewToken').value='';$('executeButton').disabled=true;$('previewBox').classList.add('d-none')}
function scopeRender(){const s=scope();$('categoryField').classList.toggle('d-none',s==='multiple_products');$('subcategoryField').classList.toggle('d-none',s!=='subcategory');$('productsField').classList.toggle('d-none',s!=='multiple_products');invalidate()}
function productsRender(){$('selectedProducts').innerHTML=[...selected.values()].map(p=>`<span class="badge text-bg-light border p-2">${esc(p.name)} <button type="button" class="btn-close ms-1" style="font-size:.55rem" data-remove="${p.id}"></button><input type="hidden" name="product_ids[]" value="${p.id}"></span>`).join('');document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{selected.delete(Number(b.dataset.remove));productsRender();invalidate()})}
document.querySelectorAll('[name=scope_type]').forEach(r=>r.onchange=scopeRender);document.querySelectorAll('[name=action_type]').forEach(r=>r.onchange=()=>{reasonsRender();invalidate()});form.querySelectorAll('select,textarea').forEach(el=>el.addEventListener('change',invalidate));
$('categoryId').addEventListener('change',async()=>{invalidate();$('subcategoryId').innerHTML='<option value="">در حال دریافت…</option>';if(!$('categoryId').value)return;const res=await fetch(`${routes.children}/${$('categoryId').value}/children`,{headers:{Accept:'application/json'}}),data=await res.json();$('subcategoryId').innerHTML='<option value="">انتخاب کنید</option>'+data.data.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')});
$('productSearch').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(async()=>{const q=$('productSearch').value.trim();if(q.length<2)return;$('searchResults').innerHTML='در حال جستجو…';aborter?.abort();aborter=new AbortController();try{const res=await fetch(`${routes.search}?q=${encodeURIComponent(q)}`,{signal:aborter.signal,headers:{Accept:'application/json'}}),data=await res.json();$('searchResults').innerHTML=data.data.map(p=>`<button type="button" class="list-group-item list-group-item-action" data-product="${p.id}"><b>${esc(p.name)}</b> <small>${esc(p.code||'—')}</small></button>`).join('')||'<div class="list-group-item text-muted">نتیجه‌ای یافت نشد.</div>';document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>{const p=data.data.find(x=>x.id===Number(b.dataset.product));selected.set(p.id,p);productsRender();$('searchResults').innerHTML='';invalidate()})}catch(e){if(e.name!=='AbortError')$('searchResults').innerHTML='خطا در جستجو'}},300)});
$('previewButton').onclick=async()=>{invalidate();const res=await fetch(routes.preview,{method:'POST',headers:{Accept:'application/json','X-CSRF-TOKEN':form.querySelector('[name=_token]').value},body:new FormData(form)}),data=await res.json();if(!res.ok){alert(data.message||Object.values(data.errors||{}).flat().join('\n'));return}$('previewToken').value=data.preview_token;$('previewSummary').innerHTML=[['کالاهای هدف',data.products_count],['تنوع ساختاری فعال',data.structurally_active_variants],['تغییر واقعی',data.effective_changes],['از قبل در وضعیت مطلوب',data.already_desired],['غیرقابل تغییر',data.unable_to_change]].map(x=>`<div class="col-md"><div class="border rounded p-2"><small>${x[0]}</small><div class="fw-bold">${x[1]}</div></div></div>`).join('');$('previewWarning').textContent=`این عملیات روی ${data.products_count} کالا و ${data.effective_changes} تنوع اثر می‌گذارد.`;$('previewSample').textContent=data.sample.length?'نمونه: '+data.sample.map(x=>`${x.product} / ${x.variant}`).join('، ')+(data.effective_changes>20?` و ${data.effective_changes-20} مورد دیگر`:''):'هیچ مورد قابل تغییری وجود ندارد.';$('previewBox').classList.remove('d-none');$('executeButton').disabled=data.effective_changes===0};
form.addEventListener('submit',e=>{if(!$('previewToken').value){e.preventDefault();alert('ابتدا پیش‌نمایش عملیات را مشاهده کنید.')}});reasonsRender();scopeRender();
</script>
@endsection
