@extends('layouts.app')

@section('content')
@php $actions=\App\Models\ProductDeactivationDocument::actionLabels(); $allReasons=array_merge(\App\Models\ProductDeactivationDocument::reasonLabels(),\App\Models\ProductDeactivationDocument::activationReasonLabels()); @endphp
<div class="d-flex justify-content-between align-items-center mb-3"><h4 class="mb-0">جزئیات تغییر وضعیت فروش</h4><a href="{{ route('product-deactivation-documents.index') }}" class="btn btn-outline-secondary">بازگشت</a></div>
<div class="card mb-3"><div class="card-body"><div class="row g-3"><div class="col-md-3"><b>شماره سند:</b> {{ $document->document_number }}</div><div class="col-md-3"><b>عملیات:</b> {{ $actions[$document->action_type ?? 'deactivate'] }}</div><div class="col-md-3"><b>محدوده:</b> {{ ($document->scope_type ?? 'product')==='variants'?'تنوع‌های مشخص':'کل کالا' }}</div><div class="col-md-3"><b>ثبت‌کننده:</b> {{ $document->creator?->name ?? '—' }}</div><div class="col-12"><b>دلیل تغییر وضعیت:</b> {{ $allReasons[$document->reason_type] ?? $document->reason_type }} @if($document->reason_text)<span class="text-muted">— {{ $document->reason_text }}</span>@endif</div></div></div></div>
<div class="card mb-3"><div class="card-header bg-white fw-bold">Snapshot تنوع‌ها</div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>کالا</th><th>تنوع</th><th>وضعیت قبلی فروش</th><th>وضعیت جدید فروش</th></tr></thead><tbody>@forelse($document->items as $item)<tr><td>{{ $item->product_name_snapshot ?: $item->product?->name }}</td><td>{{ $item->variant_name_snapshot ?: $item->variant?->variant_name }}</td><td>{{ $item->previous_sales_enabled===null?'نامشخص':($item->previous_sales_enabled?'فعال':'غیرفعال') }}</td><td>{{ $item->new_sales_enabled===null?(($item->action_type ?? 'deactivate')==='activate'?'فعال':'غیرفعال'):($item->new_sales_enabled?'فعال':'غیرفعال') }}</td></tr>@empty<tr><td colspan="4" class="text-muted text-center">این رویداد فقط وضعیت سطح کالا را تغییر داده است.</td></tr>@endforelse</tbody></table></div></div>
<div class="card"><div class="card-header bg-white fw-bold">تاریخچه وضعیت</div><div class="card-body"><div class="border-start ps-3">@foreach($history as $event)<div class="mb-3"><div class="fw-bold">{{ optional($event->created_at)->format('Y/m/d H:i') }} — {{ $actions[$event->action_type ?? 'deactivate'] }}</div><div>{{ $allReasons[$event->reason_type] ?? $event->reason_type }} @if($event->reason_text)— {{ $event->reason_text }}@endif</div><small class="text-muted">توسط {{ $event->creator?->name ?? '—' }} | {{ $event->document_number }}</small></div>@endforeach</div></div></div>
@endsection
