@extends('layouts.app')
@section('content')
<div class="container-fluid" dir="rtl">
 <div class="d-flex justify-content-between mb-3"><h4>نمایش سند انبارگردانی</h4><a href="{{ route('stocktake.index') }}" class="btn btn-outline-secondary">بازگشت</a></div>
 <div class="card mb-3"><div class="card-body row g-3"><div class="col-md-2"><b>شماره:</b> {{ $document->document_number }}</div><div class="col-md-2"><b>نوع:</b> انبارگردانی محصولی</div><div class="col-md-2"><b>وضعیت:</b> {{ $document->status==='draft'?'پیش‌نویس':($document->status==='cancelled'?'لغوشده':'اعمال‌شده') }}</div><div class="col-md-3"><b>انبار:</b> {{ $document->warehouse?->name }}</div><div class="col-md-3"><b>محصول:</b> {{ $document->product?->name }}</div><div class="col-12"><b>توضیحات:</b> {{ $document->description ?: '—' }}</div></div></div>
 <div class="row g-2 mb-3"><div class="col"><div class="alert alert-light">کل تنوع‌ها: {{ $document->variants_count }}</div></div><div class="col"><div class="alert alert-light">شمارش‌شده: {{ $document->counted_count }}</div></div><div class="col"><div class="alert alert-light">صفرشده: {{ $document->zeroed_count }}</div></div><div class="col"><div class="alert alert-success">جمع افزایش: {{ $document->total_increase }}</div></div><div class="col"><div class="alert alert-danger">جمع کاهش: {{ $document->total_decrease }}</div></div></div>
 <div class="card"><div class="card-body table-responsive"><table class="table table-sm table-bordered"><thead><tr><th>تنوع</th><th>SKU</th><th>موجودی آزاد قبل</th><th>رزرو</th><th>فیزیکی مورد انتظار</th><th>واقعی</th><th>آزاد بعد</th><th>اختلاف</th><th>توضیح</th></tr></thead><tbody>@foreach($document->items as $item)<tr><td>{{ $item->variant_name_snapshot ?: $item->variant?->variant_name }}</td><td>{{ $item->sku_snapshot }}</td><td>{{ $item->system_available_at_start }}</td><td>{{ $item->reserved_at_start }}</td><td>{{ $item->expected_physical_at_start }}</td><td>{{ $item->actual_quantity }}</td><td>{{ $item->new_available }}</td><td>{{ $item->difference_quantity }}</td><td>{{ $item->description }}</td></tr>@endforeach</tbody></table></div></div>
</div>
@endsection
