<?php
namespace App\Services\Integrations;
use App\Models\{Customer,PreinvoiceOrder,PreinvoiceOrderItem,ProductVariant}; use App\Models\Integration\IntegrationInboundEvent; use App\Services\DocumentCodeGenerator; use App\Services\WarehouseStockService; use Illuminate\Support\Arr; use Illuminate\Support\Facades\DB; use Illuminate\Validation\ValidationException;
class WebsiteOrderInboundService {
 public function handle(array $payload, string $headerEventId): array { $eventId=(string)($payload['event_id']??$headerEventId); $hash=hash('sha256', json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)); $order=$payload['order']??[]; $external=(string)($order['external_order_id']??''); if($external==='') throw ValidationException::withMessages(['order.external_order_id'=>'required']);
  return DB::transaction(function() use($payload,$eventId,$hash,$order,$external){ $existing=PreinvoiceOrder::where('external_order_id',$external)->lockForUpdate()->first(); $in=IntegrationInboundEvent::where('event_id',$eventId)->lockForUpdate()->first(); if($existing){ if($in && $in->payload_hash!==$hash) return ['code'=>409,'body'=>$this->resp(false,$eventId,'conflict',['payload_changed'])]; IntegrationInboundEvent::firstOrCreate(['event_id'=>$eventId],['source'=>'ariya_site','event_type'=>$payload['event_type']??'order.created','payload_hash'=>$hash,'status'=>'processed','external_reference'=>$external,'response_code'=>200,'processed_at'=>now()]); return ['code'=>200,'body'=>$this->docResp($eventId,'already_processed',$existing)]; }
   if(($order['status']??'')!=='paid' || Arr::get($order,'payment.status')!=='paid') return ['code'=>422,'body'=>$this->resp(false,$eventId,'rejected',[['code'=>'order_not_paid']])];
   $errors=[]; $resolved=[]; foreach(($order['items']??[]) as $i=>$item){ $q=max(1,(int)($item['quantity']??1)); $v=$this->variant($item); if(!$v){$errors[]=['item_index'=>$i,'external_variant_id'=>$item['external_variant_id']??null,'code'=>'variant_not_found','message'=>'Variant mapping was not found.']; continue;} $v=ProductVariant::whereKey($v->id)->lockForUpdate()->first(); if((int)$v->stock<$q){$errors[]=['item_index'=>$i,'external_variant_id'=>$item['external_variant_id']??null,'code'=>'insufficient_stock','requested'=>$q,'available'=>(int)$v->stock,'message'=>'Insufficient sellable stock.']; continue;} $resolved[]=[$v,$q,max(0,(int)($item['unit_price']??0)),max(0,(int)($item['line_discount_amount']??0))]; }
   if($errors||!$resolved){ IntegrationInboundEvent::create(['event_id'=>$eventId,'source'=>'ariya_site','event_type'=>$payload['event_type']??'order.created','payload_hash'=>$hash,'status'=>'rejected','external_reference'=>$external,'response_code'=>422,'error'=>json_encode($errors,JSON_UNESCAPED_UNICODE)]); return ['code'=>422,'body'=>$this->resp(false,$eventId,'rejected',$errors)]; }
   $cdata=$order['customer']??[]; $mobile=(string)($cdata['mobile']??''); $customer=$mobile?Customer::firstOrCreate(['mobile'=>$mobile],['first_name'=>$cdata['name']??'مشتری','address'=>$cdata['address']??null,'province_id'=>$cdata['province_id']??null,'city_id'=>$cdata['city_id']??null,'sync_source'=>'ariya_site','crm_customer_id'=>$cdata['external_customer_id']??null]):null;
   $pre=PreinvoiceOrder::create(['uuid'=>DocumentCodeGenerator::generateUnique5DigitCode(PreinvoiceOrder::class),'external_order_id'=>$external,'status'=>PreinvoiceOrder::STATUS_PENDING_FINANCE,'customer_id'=>$customer?->id,'customer_name'=>$cdata['name']??'مشتری سایت','customer_mobile'=>$mobile,'customer_address'=>$cdata['address']??null,'province_id'=>$cdata['province_id']??null,'city_id'=>$cdata['city_id']??null,'shipping_price'=>max(0,(int)Arr::get($order,'shipping.amount',0)),'discount_amount'=>max(0,(int)($order['discount_amount']??0)),'total_price'=>max(0,(int)($order['total_amount']??0)),'description'=>'Ariya site order '.$external]);
   foreach($resolved as [$v,$q,$price,$disc]){ PreinvoiceOrderItem::create(['preinvoice_order_id'=>$pre->id,'product_id'=>$v->product_id,'variant_id'=>$v->id,'quantity'=>$q,'price'=>$price,'line_discount_amount'=>$disc]); WarehouseStockService::change(WarehouseStockService::centralWarehouseId(),$v->product_id,-$q,$v->id); $v->refresh(); $v->reserved=(int)$v->reserved+$q; $v->save(); }
   IntegrationInboundEvent::create(['event_id'=>$eventId,'source'=>'ariya_site','event_type'=>$payload['event_type']??'order.created','payload_hash'=>$hash,'status'=>'processed','external_reference'=>$external,'response_code'=>200,'processed_at'=>now()]); return ['code'=>200,'body'=>$this->docResp($eventId,'accepted',$pre)]; }); }
 private function variant(array $item): ?ProductVariant { $ext=(string)($item['external_variant_id']??''); return ProductVariant::when($ext!=='' && ctype_digit($ext),fn($q)=>$q->orWhere('variety_id',(int)$ext))->when($ext!=='',fn($q)=>$q->orWhere('variant_code',$ext))->when(!empty($item['variant_code']),fn($q)=>$q->orWhere('variant_code',$item['variant_code']))->first(); }
 private function docResp($e,$s,$d){return ['ok'=>true,'event_id'=>$e,'status'=>$s,'document'=>['type'=>'preinvoice','id'=>$d->id,'uuid'=>$d->uuid]];} private function resp($ok,$e,$s,$errs){return ['ok'=>$ok,'event_id'=>$e,'status'=>$s,'errors'=>$errs];}
}
