@if(($activeTab ?? 'preinvoices') === 'preinvoices')
  @foreach($orders as $o)
    <div class="modal fade" id="returnModal{{ $o->id }}" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="POST" action="{{ route('preinvoice.draft.return',$o->uuid) }}" data-guard-submit>@csrf<div class="modal-header"><h6 class="modal-title">ارجاع به فروشنده - {{ $o->uuid }}</h6><button type="button" class="btn-close ms-0 me-auto" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">علت ارجاع</label><select class="form-select" name="reason" required data-other-toggle="returnOther{{ $o->id }}">@foreach($preinvoiceReturnReasons as $r)<option value="{{ $r }}">{{ $r }}</option>@endforeach</select><label class="form-label mt-3">توضیحات ارجاع</label><textarea id="returnOther{{ $o->id }}" class="form-control" name="note" rows="3"></textarea></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">انصراف</button><button class="btn btn-warning">ارجاع به فروشنده</button></div></form></div></div>
    <div class="modal fade" id="cancelModal{{ $o->id }}" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="POST" action="{{ route('preinvoice.draft.cancel',$o->uuid) }}" data-guard-submit>@csrf<div class="modal-header"><h6 class="modal-title text-danger">لغو پیش‌فاکتور - {{ $o->uuid }}</h6><button type="button" class="btn-close ms-0 me-auto" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="alert alert-warning small">با لغو پیش‌فاکتور، رزرو موجودی آزاد می‌شود و این سند دیگر در صف مالی نمایش داده نخواهد شد.</div><label class="form-label">علت لغو</label><select class="form-select" name="reason" required data-other-toggle="cancelOther{{ $o->id }}">@foreach($preinvoiceCancelReasons as $r)<option value="{{ $r }}">{{ $r }}</option>@endforeach</select><label class="form-label mt-3">توضیحات</label><textarea id="cancelOther{{ $o->id }}" class="form-control" name="note" rows="3"></textarea></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">انصراف</button><button class="btn btn-danger">لغو پیش‌فاکتور</button></div></form></div></div>
  @endforeach
@elseif(($activeTab ?? '') === 'reapprovals')
  @foreach($financeReapprovalInvoices as $invoice)
    @include('preinvoice.partials.finance-reapproval-changes', ['invoice' => $invoice, 'changes' => $financeReapprovalChanges[$invoice->id]])
    <div class="modal fade" id="invoiceReturn{{ $invoice->id }}" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="POST" action="{{ route('finance.invoices.return-to-sales',$invoice->uuid) }}" data-guard-submit>@csrf<div class="modal-header"><h6 class="modal-title">ارجاع فاکتور برای اصلاح</h6><button type="button" class="btn-close ms-0 me-auto" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">علت</label><select class="form-select" name="reason" required data-other-toggle="invoiceOther{{ $invoice->id }}">@foreach($invoiceReturnReasons as $r)<option value="{{ $r }}">{{ $r }}</option>@endforeach</select><label class="form-label mt-3">توضیحات</label><textarea id="invoiceOther{{ $invoice->id }}" class="form-control" name="note" rows="3"></textarea></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">انصراف</button><button class="btn btn-warning">ارجاع برای اصلاح</button></div></form></div></div>
  @endforeach
@endif
