@if(($activeTab ?? 'preinvoices') === 'preinvoices')
  @foreach($orders as $o)
    <div class="modal fade" id="returnModal{{ $o->id }}" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="POST" action="{{ route('preinvoice.draft.return',$o->uuid) }}" data-guard-submit>@csrf<div class="modal-header"><h6 class="modal-title">ارجاع به فروشنده - {{ $o->uuid }}</h6><button type="button" class="btn-close ms-0 me-auto" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">علت ارجاع</label><select class="form-select" name="reason" required data-other-toggle="returnOther{{ $o->id }}">@foreach($preinvoiceReturnReasons as $r)<option value="{{ $r }}">{{ $r }}</option>@endforeach</select><label class="form-label mt-3">توضیحات ارجاع</label><textarea id="returnOther{{ $o->id }}" class="form-control" name="note" rows="3"></textarea></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">انصراف</button><button class="btn btn-warning">ارجاع به فروشنده</button></div></form></div></div>
    <div class="modal fade" id="cancelModal{{ $o->id }}" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="POST" action="{{ route('preinvoice.draft.cancel',$o->uuid) }}" data-guard-submit>@csrf<div class="modal-header"><h6 class="modal-title text-danger">لغو پیش‌فاکتور - {{ $o->uuid }}</h6><button type="button" class="btn-close ms-0 me-auto" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="alert alert-warning small">با لغو پیش‌فاکتور، رزرو موجودی آزاد می‌شود و این سند دیگر در صف مالی نمایش داده نخواهد شد.</div><label class="form-label">علت لغو</label><select class="form-select" name="reason" required data-other-toggle="cancelOther{{ $o->id }}">@foreach($preinvoiceCancelReasons as $r)<option value="{{ $r }}">{{ $r }}</option>@endforeach</select><label class="form-label mt-3">توضیحات</label><textarea id="cancelOther{{ $o->id }}" class="form-control" name="note" rows="3"></textarea></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">انصراف</button><button class="btn btn-danger">لغو پیش‌فاکتور</button></div></form></div></div>
  @endforeach
@else
  @foreach($financeReapprovalInvoices as $invoice)
    <div class="modal fade" id="invoiceChanges{{ $invoice->id }}" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h6 class="modal-title">تغییرات فاکتور {{ $invoice->uuid }}</h6><button type="button" class="btn-close ms-0 me-auto" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="alert alert-info small">در ساختار فعلی snapshot قبل از تغییر برای مقایسه دقیق وجود ندارد؛ اطلاعات قطعی فعلی نمایش داده می‌شود.</div><div class="row g-2 mb-3"><div class="col-md-4"><span class="text-muted">مبلغ جدید:</span> {{ number_format((int)$invoice->total) }} ریال</div><div class="col-md-4"><span class="text-muted">تغییر‌دهنده:</span> {{ $invoice->statusChangedByUser?->name ?? $invoice->preinvoiceOrder?->creator?->name ?? '—' }}</div><div class="col-md-4"><span class="text-muted">زمان تغییر:</span> {{ $invoice->items_updated_at ? Morilog\Jalali\Jalalian::fromDateTime($invoice->items_updated_at)->format('Y/m/d H:i') : '—' }}</div></div><div class="table-responsive"><table class="table table-sm"><thead><tr><th>کالا</th><th>تنوع</th><th>تعداد</th><th>قیمت snapshot</th><th>تخفیف</th><th>مبلغ ردیف</th></tr></thead><tbody>@foreach($invoice->items as $it)<tr><td>{{ $it->product?->name ?? '—' }}</td><td>{{ $it->variant?->variant_name ?? '—' }}</td><td>{{ number_format((int)$it->quantity) }}</td><td>{{ number_format((int)$it->price) }}</td><td>{{ number_format((int)($it->line_discount_amount ?? 0)) }}</td><td>{{ number_format((int)($it->line_total ?? ((int)$it->quantity*(int)$it->price))) }}</td></tr>@endforeach</tbody></table></div></div></div></div></div>
    <div class="modal fade" id="invoiceReturn{{ $invoice->id }}" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="POST" action="{{ route('finance.invoices.return-to-sales',$invoice->uuid) }}" data-guard-submit>@csrf<div class="modal-header"><h6 class="modal-title">ارجاع فاکتور برای اصلاح</h6><button type="button" class="btn-close ms-0 me-auto" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">علت</label><select class="form-select" name="reason" required data-other-toggle="invoiceOther{{ $invoice->id }}">@foreach($invoiceReturnReasons as $r)<option value="{{ $r }}">{{ $r }}</option>@endforeach</select><label class="form-label mt-3">توضیحات</label><textarea id="invoiceOther{{ $invoice->id }}" class="form-control" name="note" rows="3"></textarea></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">انصراف</button><button class="btn btn-warning">ارجاع برای اصلاح</button></div></form></div></div>
  @endforeach
@endif
