@extends('layouts.app')
@section('title', 'پیش‌نمایش پورسانت')
@section('content')
<div class="container-fluid py-4">
 <div class="d-flex justify-content-between mb-4"><div><h1 class="h3">پیش‌نمایش محاسبه پورسانت</h1><p class="text-muted">این محاسبه در دیتابیس ذخیره نشده است.</p></div><a class="btn btn-outline-secondary" href="{{ route('finance.seller-sales.create') }}">بازگشت</a></div>
 <div class="row g-3 mb-4">@foreach($summary as $row)<div class="col-xl-4 col-md-6"><div class="card shadow-sm h-100"><div class="card-body"><h2 class="h5 mb-3">{{ $row['seller'] }}</h2><dl class="row mb-0"><dt class="col-6">تعداد فاکتور</dt><dd class="col-6">{{ number_format($row['invoice_count']) }}</dd><dt class="col-6">جمع فروش</dt><dd class="col-6">{{ number_format($row['sales']) }} ریال</dd><dt class="col-6">پورسانت پایه</dt><dd class="col-6">{{ number_format($row['base_commission']) }} ریال</dd><dt class="col-6">پورسانت کمپین</dt><dd class="col-6">{{ number_format($row['campaign_commission']) }} ریال</dd><dt class="col-6">پورسانت نهایی</dt><dd class="col-6 fw-bold text-success">{{ number_format($row['final_commission']) }} ریال</dd></dl></div></div></div>@endforeach</div>
 <div class="card shadow-sm overflow-hidden"><div class="card-header bg-white"><h2 class="h5 mb-0">جزئیات فاکتورها</h2></div><div class="table-responsive"><table class="table table-striped align-middle mb-0"><thead class="table-light"><tr><th>شماره فاکتور</th><th>مشتری</th><th>فروشنده</th><th>مبلغ فروش</th><th>نرخ پورسانت</th><th>مبلغ پورسانت</th></tr></thead><tbody>@foreach($invoiceRows as $row)<tr><td class="fw-semibold">{{ $row['number'] }}</td><td>{{ $row['customer'] }}</td><td>{{ $row['seller'] }}</td><td>{{ number_format($row['sales']) }} ریال</td><td>{{ number_format($row['rate'], 4) }}٪</td><td class="fw-semibold">{{ number_format($row['commission']) }} ریال</td></tr>@endforeach</tbody></table></div></div>
 <form method="POST" action="{{ route('finance.seller-sales.store') }}" class="mt-4 text-end">@csrf<input type="hidden" name="user_id" value="{{ $sellerId }}"><input type="hidden" name="date_from" value="{{ $dateFrom }}"><input type="hidden" name="date_to" value="{{ $dateTo }}">@foreach($invoiceIds as $invoiceId)<input type="hidden" name="invoice_ids[]" value="{{ $invoiceId }}">@endforeach @foreach($manualInvoiceIds as $invoiceId)<input type="hidden" name="manual_invoice_ids[]" value="{{ $invoiceId }}">@endforeach<button class="btn btn-success btn-lg">ثبت گزارش پورسانت</button></form>
</div>
@endsection
