@extends('layouts.app')
@section('title', 'گزارش مالی پورسانت')
@section('content')
<div class="container-fluid py-4" id="commissionReport" data-list-url="{{ route('finance.seller-sales.report-invoices') }}" data-manual-url="{{ route('finance.seller-sales.manual-invoice') }}">
 <div class="d-flex justify-content-between mb-4"><div><h1 class="h3">گزارش مالی پورسانت</h1><p class="text-muted">انتخاب فاکتور و پیش‌نمایش محاسبه، بدون ثبت سند</p></div><button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#manualModal">افزودن دستی فاکتور</button></div>
 <div class="card shadow-sm mb-4"><div class="card-body"><form id="filters" class="row g-3 align-items-end">
  <div class="col-md-3"><label class="form-label">از تاریخ</label><input class="form-control" id="dateFrom" name="date_from" data-jdp required></div>
  <div class="col-md-3"><label class="form-label">تا تاریخ</label><input class="form-control" id="dateTo" name="date_to" data-jdp required></div>
  <div class="col-md-4"><label class="form-label">شماره فاکتور یا نام مشتری</label><input class="form-control" name="search" maxlength="100"></div>
  <div class="col-md-2"><button class="btn btn-primary w-100">نمایش فاکتورها</button></div>
 </form><div class="alert alert-danger d-none mt-3 mb-0" id="reportError"></div></div></div>
 <div class="card shadow-sm overflow-hidden"><div class="card-header bg-white d-flex flex-wrap justify-content-between gap-2"><div><strong id="selectedCount">۰ فاکتور انتخاب شده</strong> — <strong id="selectedTotal">۰ ریال فروش</strong></div><label><input type="checkbox" class="form-check-input" id="selectPage"> انتخاب همه این صفحه</label></div>
  <div class="table-responsive"><table class="table table-striped table-hover align-middle mb-0"><thead class="table-light"><tr><th></th><th>شماره فاکتور</th><th>تاریخ</th><th>مشتری</th><th>فروشنده</th><th>مبلغ</th><th>وضعیت پرداخت</th></tr></thead><tbody id="invoiceRows"><tr><td colspan="7" class="text-center py-5 text-muted">ابتدا بازه تاریخ را انتخاب کنید.</td></tr></tbody></table></div>
  <div class="card-footer bg-white d-flex justify-content-between"><button class="btn btn-sm btn-outline-secondary" id="prev" disabled>قبلی</button><span id="pageLabel">—</span><button class="btn btn-sm btn-outline-secondary" id="next" disabled>بعدی</button></div>
 </div>
 <form method="POST" action="{{ route('finance.seller-sales.preview') }}" id="previewForm" class="sticky-bottom bg-white border rounded shadow p-3 mt-4"><div id="selectedInputs"></div><input type="hidden" name="date_from" id="previewFrom"><input type="hidden" name="date_to" id="previewTo">@csrf<div class="d-flex justify-content-between align-items-center"><span class="text-muted">در این مرحله هیچ رکوردی ذخیره نمی‌شود.</span><button class="btn btn-success" id="previewButton" disabled>مشاهده محاسبه پورسانت</button></div></form>
</div>
<div class="modal fade" id="manualModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title fs-5">افزودن دستی فاکتور</h2><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">شماره پنج‌رقمی فاکتور</label><div class="input-group"><input class="form-control" id="manualNumber" maxlength="5" inputmode="numeric"><button class="btn btn-primary" id="findManual">جستجو</button></div><div class="alert alert-danger d-none mt-3" id="manualError"></div><div id="manualResult" class="mt-3"></div></div></div></div></div>
@endsection
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded',()=>{const root=document.getElementById('commissionReport'),e=id=>document.getElementById(id),chosen=new Map(),nf=new Intl.NumberFormat('fa-IR');let rows=[],page=1,last=1;const esc=v=>String(v??'—').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const sync=()=>{let total=[...chosen.values()].reduce((s,x)=>s+Number(x.total),0);e('selectedCount').textContent=`${nf.format(chosen.size)} فاکتور انتخاب شده`;e('selectedTotal').textContent=`${nf.format(total)} ریال فروش`;e('selectedInputs').innerHTML=[...chosen.values()].map(x=>`<input type="hidden" name="invoice_ids[]" value="${x.id}">${x.outside_range?`<input type="hidden" name="manual_invoice_ids[]" value="${x.id}">`:''}`).join('');e('previewFrom').value=e('dateFrom').value;e('previewTo').value=e('dateTo').value;e('previewButton').disabled=!chosen.size;e('selectPage').checked=rows.length>0&&rows.every(x=>chosen.has(Number(x.id)))};
const render=()=>{e('invoiceRows').innerHTML=rows.length?rows.map(x=>`<tr><td><input class="form-check-input choice" type="checkbox" value="${x.id}" ${chosen.has(Number(x.id))?'checked':''}></td><td><b>${esc(x.number)}</b></td><td>${esc(x.date)}</td><td>${esc(x.customer)}</td><td>${esc(x.seller)}</td><td>${nf.format(x.total)} ریال</td><td>${esc(x.payment_status)}</td></tr>`).join(''):'<tr><td colspan="7" class="text-center py-5">فاکتوری یافت نشد.</td></tr>';document.querySelectorAll('.choice').forEach(i=>i.onchange=()=>{let x=rows.find(x=>x.id==i.value);i.checked?chosen.set(Number(x.id),x):chosen.delete(Number(x.id));sync()});e('pageLabel').textContent=`صفحه ${nf.format(page)} از ${nf.format(last)}`;e('prev').disabled=page<=1;e('next').disabled=page>=last;sync()};
const load=async p=>{let q=new URLSearchParams(new FormData(e('filters')));q.set('page',p);e('reportError').classList.add('d-none');try{let r=await fetch(`${root.dataset.listUrl}?${q}`,{headers:{Accept:'application/json'}}),j=await r.json();if(!r.ok)throw Error(Object.values(j.errors||{}).flat().join(' ')||j.message);rows=j.data;page=j.current_page;last=j.last_page;render()}catch(x){e('reportError').textContent=x.message;e('reportError').classList.remove('d-none')}};
e('filters').onsubmit=x=>{x.preventDefault();load(1)};e('prev').onclick=()=>load(page-1);e('next').onclick=()=>load(page+1);e('selectPage').onchange=x=>{rows.forEach(r=>x.target.checked?chosen.set(Number(r.id),r):chosen.delete(Number(r.id)));sync()};
e('findManual').onclick=async()=>{e('manualError').classList.add('d-none');e('manualResult').innerHTML='';try{let q=new URLSearchParams({invoice_number:e('manualNumber').value,date_from:e('dateFrom').value,date_to:e('dateTo').value}),r=await fetch(`${root.dataset.manualUrl}?${q}`,{headers:{Accept:'application/json'}}),x=await r.json();if(!r.ok)throw Error(r.status===404?'فاکتور معتبر پیدا نشد.':Object.values(x.errors||{}).flat().join(' ')||x.message);e('manualResult').innerHTML=`<div class="card"><div class="card-body"><div class="d-flex justify-content-between"><b>فاکتور ${esc(x.number)}</b>${x.outside_range?'<span class="badge bg-warning text-dark">خارج از بازه انتخابی</span>':''}</div><div class="row g-2 mt-2"><div class="col">${esc(x.date)}</div><div class="col">${esc(x.customer)}</div><div class="col">${esc(x.seller)}</div><div class="col">${nf.format(x.total)} ریال</div></div><button class="btn btn-success mt-3" id="addManual">افزودن</button></div></div>`;e('addManual').onclick=()=>{chosen.set(Number(x.id),x);sync();bootstrap.Modal.getOrCreateInstance(e('manualModal')).hide()}}catch(x){e('manualError').textContent=x.message;e('manualError').classList.remove('d-none')}};sync()});
</script>
@endpush
