@extends('layouts.app')
@php use App\Models\SalesReturnDocument; use Morilog\Jalali\Jalalian; $statuses=['all'=>'همه','draft'=>'پیش‌نویس‌ها','applied'=>'اعمال‌شده‌ها','cancelled'=>'لغوشده‌ها']; $sourceLabels=SalesReturnDocument::sourceTypeLabels(); $statusLabels=['draft'=>'پیش‌نویس','applied'=>'اعمال‌شده','cancelled'=>'لغوشده']; @endphp
@section('content')
<style>.sr-card{border:1px solid #e5e7eb;border-radius:10px;background:#fff}.sr-badge{border-radius:999px;padding:.25rem .55rem;font-size:.75rem}.sr-draft{background:#fff7ed;color:#9a3412}.sr-applied{background:#ecfdf5;color:#166534}.sr-cancelled{background:#f1f5f9;color:#475569}@media(max-width:767px){.sr-table thead{display:none}.sr-table,.sr-table tbody,.sr-table tr,.sr-table td{display:block;width:100%}.sr-table tr{border:1px solid #e5e7eb;border-radius:10px;margin-bottom:.75rem;padding:.5rem}.sr-table td{border:0!important;padding:.25rem .5rem}}</style>
<div class="container-fluid" dir="rtl" data-module="new-sales-return">
 <div class="d-flex justify-content-between align-items-start flex-wrap gap-2 mb-3"><div><h4>برگشت از فروش</h4><div class="text-muted small">مدیریت و گزارش اسناد برگشت داخلی و سازه‌حساب</div></div><div class="d-flex gap-1 flex-wrap">@canPermission('sales_returns.create')<a class="btn btn-sm btn-primary" href="{{ route('vouchers.return-from-sale.create') }}">ثبت برگشت جدید</a>@endcanPermission @canPermission('sales_returns.export')<a class="btn btn-sm btn-outline-success" href="{{ route('vouchers.return-from-sale.export.excel',request()->query()) }}">خروجی Excel</a><a class="btn btn-sm btn-outline-danger" href="{{ route('vouchers.return-from-sale.export.pdf',request()->query()) }}">خروجی PDF</a>@endcanPermission @canPermission('sales_returns.print')<a class="btn btn-sm btn-outline-secondary" href="{{ route('vouchers.return-from-sale.print-report',request()->query()) }}">چاپ گزارش</a>@endcanPermission<a class="btn btn-sm btn-light" href="{{ url()->previous() }}">بازگشت</a></div></div>
 <div class="alert alert-info py-2 small">اسناد جدید از جدول sales_return_documents خوانده می‌شوند و سوابق قدیمی برگشت از فروش به‌صورت Read-only از حواله‌های قدیمی نمایش داده می‌شوند و با گزارش جدید مخلوط نشده‌اند.</div>
 <div class="row g-2 mb-3">@foreach(['documents_count'=>'تعداد کل اسناد','applied_count'=>'تعداد Applied','total_refund_amount'=>'مبلغ کل بستانکاری Applied','healthy_amount'=>'مبلغ کالاهای سالم Applied','damaged_amount'=>'مبلغ کالاهای معیوب Applied'] as $k=>$label)<div class="col-6 col-lg"><div class="sr-card p-2"><div class="text-muted small">{{ $label }}</div><div class="fw-bold">{{ number_format($summary[$k] ?? 0) }}</div></div></div>@endforeach</div>
 <ul class="nav nav-tabs mb-3">@foreach($statuses as $key=>$label)<li class="nav-item"><a class="nav-link {{ ($filters['status']??'all')===$key?'active':'' }}" href="{{ route('vouchers.return-from-sale.index',array_merge(request()->except('page'),['status'=>$key])) }}">{{ $label }} ({{ number_format($tabCounts[$key]??0) }})</a></li>@endforeach</ul>
 <form class="sr-card p-3 mb-3"><div class="row g-2">
  <div class="col-md-2"><input class="form-control form-control-sm" name="document_number" value="{{ $filters['document_number']??'' }}" placeholder="شماره سند"></div><div class="col-md-2"><select class="form-select form-select-sm" name="source_type"><option value="all">همه نوع‌ها</option>@foreach($sourceLabels as $k=>$v)<option value="{{ $k }}" @selected(($filters['source_type']??'all')===$k)>{{ $v }}</option>@endforeach</select></div><div class="col-md-2"><input class="form-control form-control-sm" name="invoice_number" value="{{ $filters['invoice_number']??'' }}" placeholder="شماره فاکتور داخلی"></div><div class="col-md-2"><input class="form-control form-control-sm" name="external_invoice_number" value="{{ $filters['external_invoice_number']??'' }}" placeholder="شماره سازه‌حساب"></div><div class="col-md-2"><input class="form-control form-control-sm" name="reference_number" value="{{ $filters['reference_number']??'' }}" placeholder="شماره مرجع"></div><div class="col-md-2"><select class="form-select form-select-sm" name="destination_warehouse_id"><option value="">همه انبارها</option>@foreach($warehouses as $w)<option value="{{ $w->id }}" @selected(($filters['destination_warehouse_id']??null)==$w->id)>{{ $w->name }}</option>@endforeach</select></div>
  <div class="col-md-2"><select class="form-select form-select-sm" name="item_condition"><option value="all">همه وضعیت کالا</option><option value="healthy" @selected(($filters['item_condition']??'all')==='healthy')>سالم</option><option value="damaged" @selected(($filters['item_condition']??'all')==='damaged')>معیوب</option></select></div><div class="col-md-2"><input type="number" class="form-control form-control-sm" name="customer_id" value="{{ $filters['customer_id']??'' }}" placeholder="شناسه مشتری"></div><div class="col-md-2"><input type="number" class="form-control form-control-sm" name="product_id" value="{{ $filters['product_id']??'' }}" placeholder="شناسه کالا"></div><div class="col-md-2"><input type="number" class="form-control form-control-sm" name="product_variant_id" value="{{ $filters['product_variant_id']??'' }}" placeholder="شناسه تنوع"></div><div class="col-md-2"><input class="form-control form-control-sm" name="date_from" value="{{ $filters['date_from']??'' }}" placeholder="از تاریخ"></div><div class="col-md-2"><input class="form-control form-control-sm" name="date_to" value="{{ $filters['date_to']??'' }}" placeholder="تا تاریخ"></div>
  <div class="col-md-2"><input type="number" class="form-control form-control-sm" name="min_amount" value="{{ $filters['min_amount']??'' }}" placeholder="حداقل مبلغ"></div><div class="col-md-2"><input type="number" class="form-control form-control-sm" name="max_amount" value="{{ $filters['max_amount']??'' }}" placeholder="حداکثر مبلغ"></div><div class="col-md-2"><select class="form-select form-select-sm" name="sort"><option value="newest">جدیدترین</option><option value="oldest" @selected(($filters['sort']??'')==='oldest')>قدیمی‌ترین</option><option value="amount_desc" @selected(($filters['sort']??'')==='amount_desc')>بیشترین مبلغ</option><option value="amount_asc" @selected(($filters['sort']??'')==='amount_asc')>کمترین مبلغ</option><option value="customer" @selected(($filters['sort']??'')==='customer')>نام مشتری</option></select></div><div class="col-md-4 d-flex gap-1"><button class="btn btn-sm btn-dark">اعمال فیلتر</button><a class="btn btn-sm btn-light" href="{{ route('vouchers.return-from-sale.index') }}">حذف فیلتر</a></div>
 </div></form>
 <div class="sr-card"><div class="table-responsive"><table class="table table-sm align-middle mb-0 sr-table"><thead><tr><th>ردیف</th><th>شماره سند</th><th>تاریخ</th><th>نوع</th><th>مشتری</th><th>سند مرجع</th><th>اقلام</th><th>تعداد</th><th>وضعیت کالا</th><th>انبار مقصد</th><th>مبلغ</th><th>ثبت‌کننده</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>@forelse($documents as $document)@php($cond=$reportService->healthStatusSummary($document))@php($dest=$reportService->destinationLabels($document))<tr><td>{{ $loop->iteration + ($documents->currentPage()-1)*$documents->perPage() }}</td><td>{{ $document->document_number }}</td><td>{{ $document->created_at ? Jalalian::fromDateTime($document->created_at)->format('Y/m/d H:i') : '—' }}</td><td>{{ $sourceLabels[$document->source_type]??'—' }}</td><td>{{ $document->customer?->display_name ?: '—' }}</td><td>{{ $document->isInternal() ? ($document->invoice?->uuid ?: '—') : ($document->external_invoice_number ?: '—') }}@if($document->reference_number)<div class="small text-muted">{{ $document->reference_number }}</div>@endif</td><td>{{ number_format($document->items_count) }}</td><td>{{ number_format($document->returned_quantity_sum ?? $document->total_quantity) }}</td><td><span class="sr-badge bg-light border" title="{{ $cond['details'] }}">{{ $cond['label'] }}</span></td><td><span title="{{ $dest['details'] }}">{{ $dest['label'] }}</span></td><td>{{ number_format($document->total_refund_amount) }}</td><td>{{ $document->creator?->name ?: '—' }}</td><td><span class="sr-badge sr-{{ $document->status }}">{{ $statusLabels[$document->status]??$document->status }}</span></td><td class="text-nowrap"><a class="btn btn-sm btn-outline-primary" href="{{ route('vouchers.return-from-sale.show',$document) }}">مشاهده</a>@if($document->isDraft())<a class="btn btn-sm btn-outline-secondary" href="{{ route('vouchers.return-from-sale.edit',$document) }}">ادامه ویرایش</a>@endif @if(!$document->isCancelled())<a class="btn btn-sm btn-outline-dark" href="{{ route('vouchers.return-from-sale.print',$document) }}">چاپ</a>@endif @if($document->isApplied())<a class="btn btn-sm btn-outline-danger" href="{{ route('vouchers.return-from-sale.pdf',$document) }}">PDF</a>@endif</td></tr>@empty<tr><td colspan="14" class="text-center py-4 text-muted">{{ request()->query() ? 'سندی مطابق فیلترهای انتخاب‌شده پیدا نشد.' : 'هنوز سند برگشت از فروشی ثبت نشده است.' }}</td></tr>@endforelse</tbody></table></div><div class="p-2">{{ $documents->links() }}</div></div>

 <div class="sr-card mt-3"><div class="d-flex justify-content-between align-items-center mb-2"><h6 class="mb-0">سوابق قدیمی</h6><span class="badge bg-secondary">Read-only</span></div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>شماره</th><th>تاریخ</th><th>مشتری/شرح</th><th>عملیات</th></tr></thead><tbody>@forelse($legacyReturns as $legacy)<tr><td>{{ $legacy->uuid ?? $legacy->id }}</td><td>{{ $legacy->created_at }}</td><td>{{ $legacy->customer?->display_name ?? $legacy->description ?? '—' }}</td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('vouchers.show', $legacy) }}">مشاهده</a></td></tr>@empty<tr><td colspan="4" class="text-center text-muted py-3">سابقه قدیمی ثبت نشده است.</td></tr>@endforelse</tbody></table></div><div class="p-2">{{ $legacyReturns->links() }}</div></div>
</div>
@endsection
