<?php
namespace App\Http\Controllers;
use App\Models\{Customer,Invoice,Product,ProductVariant,SalesReturnDocument,WarehouseStock};
use App\Services\SalesReturnCalculationService;
use Illuminate\Http\Request;
class SalesReturnLookupController extends Controller
{
 public function __construct(private SalesReturnCalculationService $calculator) {}
 public function customers(Request $r){ $q=trim($r->get('q','')); if(mb_strlen($q)<2) return ['results'=>[]]; $rows=Customer::query()->where(function($w)use($q){$w->where('first_name','like',"%$q%")->orWhere('last_name','like',"%$q%")->orWhere('mobile','like',"%$q%")->orWhere('id',$q);})->limit(20)->get(); return ['results'=>$rows->map(fn($c)=>['id'=>$c->id,'text'=>trim($c->first_name.' '.$c->last_name).' - '.$c->mobile,'mobile'=>$c->mobile])]; }
 public function customerInvoices(Customer $customer, Request $r){ $can=auth()->user()?->can('sales_returns.override_invoice_status')??false; $q=Invoice::withCount('items')->where('customer_id',$customer->id)->where('status','!=',Invoice::STATUS_NOT_SHIPPED); if(!$can)$q->where('status',Invoice::STATUS_SHIPPED); return ['invoices'=>$q->latest('id')->limit(50)->get()->map(fn($i)=>['id'=>$i->id,'uuid'=>$i->uuid,'date'=>$i->created_at?->format('Y-m-d'),'total'=>(int)$i->total,'items_count'=>$i->items_count,'status'=>$i->status])]; }
 public function invoiceItems(Invoice $invoice){ $invoice->load('items.product','items.variant'); $preview=$this->calculator->calculateInternalPreview($invoice,$invoice->items->map(fn($i)=>['invoice_item_id'=>$i->id,'return_quantity'=>0])->all()); $prev=$this->calculator->previouslyReturnedQuantities($invoice->items->pluck('id')->all()); return ['items'=>$invoice->items->map(fn($i)=>['invoice_item_id'=>$i->id,'product_id'=>$i->product_id,'product_name'=>$i->product?->name,'variant_id'=>$i->variant_id,'variant_name'=>$i->variant?->variant_name,'sku'=>$i->variant?->variant_code,'barcode'=>$i->variant?->variant_code,'quantity'=>(int)$i->quantity,'previously_returned'=>(int)($prev[$i->id]??0),'returnable'=>max((int)$i->quantity-(int)($prev[$i->id]??0),0),'unit_price'=>(int)$i->price])]; }
 public function products(Request $r){ $q=trim($r->get('q','')); if(mb_strlen($q)<2) return ['results'=>[]]; $rows=Product::query()->with('variants')->search($q)->limit(20)->get(); return ['results'=>$rows->map(fn($p)=>['id'=>$p->id,'text'=>$p->name.' - '.($p->code?:$p->sku),'variants'=>$p->variants->map(fn($v)=>['id'=>$v->id,'text'=>$v->variant_name,'sku'=>$v->variant_code,'buy_price'=>(int)$v->buy_price,'sell_price'=>(int)$v->sell_price])])]; }
 public function variants(Product $product){ $product->load('variants.warehouseStocks.warehouse'); return ['variants'=>$product->variants->map(fn($v)=>['id'=>$v->id,'name'=>$v->variant_name,'sku'=>$v->variant_code,'buy_price'=>(int)$v->buy_price,'sell_price'=>(int)$v->sell_price,'stocks'=>$v->warehouseStocks->map(fn($s)=>['warehouse'=>$s->warehouse?->name,'quantity'=>(int)$s->quantity])])]; }
 public function preview(Request $r){ if($r->input('source_type')===SalesReturnDocument::SOURCE_INTERNAL_INVOICE){ $invoice=Invoice::with('items')->findOrFail((int)$r->input('invoice_id')); return ['items'=>$this->calculator->calculateInternalPreview($invoice,$r->input('items',[]))]; } return ['items'=>$this->calculator->calculateSazehPreview($r->input('items',[]))]; }
}
