@extends('layouts.app')
@section('content')
@php($document=$document??null)
<div class="container-fluid" dir="rtl">
  <div class="d-flex justify-content-between align-items-center mb-3"><div><h5 class="mb-1">ثبت برگشت از فروش</h5><div class="text-muted small">ثبت برگشت براساس فاکتور داخلی یا فاکتور سازه‌حساب</div></div><a class="btn btn-sm btn-outline-secondary" href="{{ url()->previous() }}">بازگشت</a></div>
  @if($errors->any())<div class="alert alert-danger small">لطفاً خطاهای فرم را بررسی کنید.</div>@endif
  <form method="POST" action="{{ $document ? route('sales-returns.update',$document) : route('sales-returns.store') }}" id="salesReturnForm">@csrf @if($document) @method('PATCH') @endif
    <div class="row g-3">
      <div class="col-lg-3"><label class="form-label small">نوع برگشت</label><select class="form-select form-select-sm" name="source_type" id="sourceType"><option value="internal_invoice">برگشت براساس فاکتور داخلی</option><option value="sazeh_hesab">برگشت براساس فاکتور سازه‌حساب</option></select></div>
      <div class="col-lg-3"><label class="form-label small">شناسه مشتری</label><input class="form-control form-control-sm" name="customer_id" id="customerId" value="{{ old('customer_id',$document?->customer_id) }}" required><div class="form-text">جستجوی Ajax از مسیر customers/search در JS فعال است؛ ورود ID نیز مجاز است.</div></div>
      <div class="col-lg-3 internal-box"><label class="form-label small">شناسه فاکتور داخلی</label><input class="form-control form-control-sm" name="invoice_id" id="invoiceId" value="{{ old('invoice_id',$document?->invoice_id) }}"></div>
      <div class="col-lg-3 sazeh-box d-none"><label class="form-label small">شماره فاکتور سازه‌حساب</label><input class="form-control form-control-sm" name="external_invoice_number" value="{{ old('external_invoice_number',$document?->external_invoice_number) }}"></div>
      <div class="col-lg-3 sazeh-box d-none"><label class="form-label small">تاریخ فاکتور</label><input type="date" class="form-control form-control-sm" name="external_invoice_date" value="{{ old('external_invoice_date',$document?->external_invoice_date?->format('Y-m-d')) }}"></div>
      <div class="col-lg-3"><label class="form-label small">علت برگشت</label><select class="form-select form-select-sm" name="return_reason">@foreach($returnReasons as $k=>$v)<option value="{{ $k }}">{{ $v }}</option>@endforeach</select></div>
      <div class="col-lg-3"><label class="form-label small">اثر پورسانت</label><select class="form-select form-select-sm" name="commission_effect_type">@foreach($commissionEffectLabels as $k=>$v)<option value="{{ $k }}" @selected(old('commission_effect_type', $document?->commission_effect_type ?? 'commercial') === $k)>{{ $v }}</option>@endforeach</select></div>
      <div class="col-lg-3"><label class="form-label small">انبار مقصد پیش‌فرض</label><select class="form-select form-select-sm" name="default_destination_warehouse_id" id="defaultWarehouse">@foreach($warehouses as $w)<option value="{{ $w->id }}" data-type="{{ $w->type }}">{{ $w->name }}</option>@endforeach</select></div>
      <div class="col-lg-3"><label class="form-label small">شماره ارجاع</label><input class="form-control form-control-sm" name="reference_number" value="{{ old('reference_number',$document?->reference_number) }}"></div>
      <div class="col-12"><label class="form-label small">توضیحات</label><textarea class="form-control form-control-sm" name="description" rows="2">{{ old('description',$document?->description) }}</textarea></div>
    </div>
    <hr><div class="d-flex justify-content-between"><h6>اقلام برگشتی</h6><button class="btn btn-sm btn-outline-primary" type="button" id="addRow">افزودن کالا</button></div>
    <div class="table-responsive"><table class="table table-sm align-middle" id="itemsTable"><thead><tr><th>منبع/کالا</th><th>تنوع/آیتم فاکتور</th><th>تعداد</th><th>وضعیت</th><th>انبار مقصد</th><th>مبلغ واحد بستانکاری</th><th>کالای جدید</th><th></th></tr></thead><tbody></tbody></table></div>
    <div class="border rounded p-2 small bg-light" id="summary">تعداد اقلام: 0 | تعداد کل: 0 | سالم: 0 | مرجوعی: 0 | مبلغ بستانکاری: 0 ریال</div>
    <div class="mt-3 d-flex gap-2"><button class="btn btn-sm btn-primary" name="action" value="draft">ذخیره پیش‌نویس</button><button class="btn btn-sm btn-success" name="action" value="apply" onclick="return confirm('با ارسال سند، اقلام وارد صف دریافت انبار می‌شوند و موجودی فقط پس از تأیید مدیر انبار افزایش می‌یابد. ادامه می‌دهید؟')">ارسال به صف انبار</button><button class="btn btn-sm btn-outline-secondary" type="reset">پاک‌کردن فرم</button></div>
  </form>
</div>
<script>
(() => { const $=s=>document.querySelector(s), tbody=$('#itemsTable tbody'), warehouses=@json($warehouses->map(fn($w)=>['id'=>$w->id,'name'=>$w->name,'type'=>$w->type])->values()); let idx=0;
function whOptions(){return warehouses.map(w=>`<option value="${w.id}">${w.name}</option>`).join('')}
function row(){return `<tr><td><select name="items[${idx}][item_source]" class="form-select form-select-sm"><option value="invoice_item">آیتم فاکتور</option><option value="existing_product">کالای موجود</option><option value="new_product">کالای جدید</option></select></td><td><input class="form-control form-control-sm" name="items[${idx}][invoice_item_id]" placeholder="invoice_item_id"><input class="form-control form-control-sm mt-1" name="items[${idx}][product_variant_id]" placeholder="variant_id"></td><td><input type="number" min="0" class="form-control form-control-sm qty" name="items[${idx}][return_quantity]" value="1"></td><td><select name="items[${idx}][item_condition]" class="form-select form-select-sm cond"><option value="healthy">سالم</option><option value="damaged">مرجوعی / معیوب</option></select></td><td><select name="items[${idx}][destination_warehouse_id]" class="form-select form-select-sm wh">${whOptions()}</select></td><td><input type="number" min="0" class="form-control form-control-sm price" name="items[${idx}][refund_unit_price]" value="0"></td><td><textarea class="form-control form-control-sm" name="items[${idx}][new_product_payload][product_name]" placeholder="نام محصول جدید"></textarea><input class="form-control form-control-sm mt-1" name="items[${idx}][new_product_payload][variant_name]" placeholder="تنوع"><input class="form-control form-control-sm mt-1" name="items[${idx}][new_product_payload][sku]" placeholder="SKU"><select class="form-select form-select-sm mt-1" name="items[${idx}][new_product_payload][category_id]">@foreach($categories as $c)<option value="{{ $c->id }}">{{ $c->name }}</option>@endforeach</select><input class="form-control form-control-sm mt-1" name="items[${idx}][new_product_payload][purchase_price]" placeholder="قیمت خرید"><input class="form-control form-control-sm mt-1" name="items[${idx}][new_product_payload][sell_price]" placeholder="قیمت فروش"></td><td><button type="button" class="btn btn-sm btn-outline-danger rm">×</button></td></tr>`}
function summary(){let rows=[...tbody.querySelectorAll('tr')], q=0,h=0,d=0,a=0; rows.forEach(r=>{let qty=+r.querySelector('.qty').value||0, price=+r.querySelector('.price').value||0; q+=qty; a+=qty*price; (r.querySelector('.cond').value==='healthy'?h:d)+=qty}); $('#summary').textContent=`تعداد اقلام: ${rows.length} | تعداد کل: ${q} | سالم: ${h} | مرجوعی: ${d} | مبلغ بستانکاری: ${a.toLocaleString('fa-IR')} ریال`;}
$('#addRow').addEventListener('click',()=>{tbody.insertAdjacentHTML('beforeend',row()); idx++; summary();}); document.addEventListener('input',e=>{if(e.target.closest('#itemsTable'))summary();}); document.addEventListener('click',e=>{if(e.target.classList.contains('rm')){e.target.closest('tr').remove();summary();}}); $('#sourceType').addEventListener('change',e=>{document.querySelectorAll('.sazeh-box').forEach(x=>x.classList.toggle('d-none',e.target.value!=='sazeh_hesab')); document.querySelectorAll('.internal-box').forEach(x=>x.classList.toggle('d-none',e.target.value!=='internal_invoice')); tbody.innerHTML=''; summary();}); $('#addRow').click(); })();
</script>
@endsection
