@extends('layouts.app')
@php
    $customerName = $document->customer ? (trim(($document->customer->first_name ?? '').' '.($document->customer->last_name ?? '')) ?: $document->customer->mobile) : '—';
    $reference = $document->isInternal() ? ($document->invoice?->uuid ?: '—') : ($document->external_invoice_number ?: '—');
@endphp
@section('content')
<style>.doc-shell{direction:rtl}.official-doc{background:#fff;border:1px solid #dbe3ef;border-radius:14px}.doc-head{padding:18px;border-bottom:2px solid #1e3a5f;display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}.doc-title{font-size:24px;font-weight:900;color:#1e3a5f}.doc-meta{font-size:13px;color:#475569}.info-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;padding:16px}.info-box{background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:10px}.info-box small{display:block;color:#64748b}.signature-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.signature-box{border:1px dashed #94a3b8;border-radius:10px;height:90px;padding:10px;color:#64748b}@media(max-width:991.98px){.info-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.signature-grid{grid-template-columns:1fr}.table-responsive table{font-size:12px}}</style>
<div class="container-fluid doc-shell">
@include('sales-returns.partials.flash')
<div class="d-flex justify-content-between align-items-center mb-3 flex-wrap gap-2"><div><h3 class="mb-1">نمایش سند برگشت از فروش</h3><div class="text-muted small">صفحه رسمی و فقط خواندنی سند</div></div><div class="d-flex gap-2"><a class="btn btn-outline-secondary btn-sm" href="{{ route('sales-returns.index') }}">بازگشت</a>@if($document->isDraft())<a class="btn btn-outline-primary btn-sm" href="{{ route('sales-returns.edit',$document) }}">ویرایش</a>@endif<a class="btn btn-outline-dark btn-sm" href="{{ route('sales-returns.print',$document) }}">چاپ</a><a class="btn btn-outline-danger btn-sm" href="{{ route('sales-returns.pdf',$document) }}">PDF</a></div></div>
@if($document->isDraft())<div class="alert alert-warning">این سند هنوز پیش‌نویس است و هیچ اثر مالی یا انباری ندارد.</div>@endif
<div class="official-doc"><div class="doc-head"><div><div class="doc-title">برگشت از فروش</div><div class="doc-meta">شماره سند: {{ $document->document_number }} | تاریخ: {{ optional($document->created_at)->format('Y/m/d H:i') }}</div></div><div class="text-end"><span class="badge bg-secondary">{{ $document->statusLabel() }}</span><div class="doc-meta mt-2">{{ $document->sourceTypeLabel() }}</div></div></div>
<div class="info-grid"><div class="info-box"><small>مشتری</small><strong>{{ $customerName }}</strong></div><div class="info-box"><small>فاکتور مرجع</small><strong>{{ $reference }}</strong></div><div class="info-box"><small>نوع منبع</small><strong>{{ $document->sourceTypeLabel() }}</strong></div><div class="info-box"><small>علت برگشت</small><strong>{{ $document->return_reason ?: '—' }}</strong></div><div class="info-box"><small>ثبت‌کننده</small><strong>{{ $document->creator?->name ?: '—' }}</strong></div><div class="info-box"><small>اعمال‌کننده</small><strong>{{ $document->applier?->name ?: '—' }}</strong></div><div class="info-box"><small>زمان اعمال</small><strong>{{ optional($document->applied_at)->format('Y/m/d H:i') ?: '—' }}</strong></div><div class="info-box"><small>جمع بستانکاری</small><strong>{{ number_format($document->refund_total) }} ریال</strong></div><div class="info-box" style="grid-column:1/-1"><small>توضیحات</small><div>{{ $document->description ?: '—' }}</div></div></div>
<div class="table-responsive"><table class="table table-striped align-middle mb-0"><thead><tr><th>#</th><th>کالا</th><th>تنوع</th><th>تعداد</th><th>وضعیت</th><th>انبار مقصد</th><th>مبلغ واحد</th><th>مبلغ کل</th></tr></thead><tbody>@foreach($document->items as $item)<tr><td>{{ $loop->iteration }}</td><td>{{ $item->product_name_snapshot ?: $item->product?->name ?: '—' }}</td><td>{{ $item->variant_name_snapshot ?: $item->sku_snapshot ?: '—' }}</td><td>{{ number_format($item->return_quantity) }}</td><td>{{ $item->isDamaged() ? 'معیوب' : 'سالم' }}</td><td>{{ $item->destinationWarehouse?->name ?: '—' }}</td><td>{{ number_format($item->refund_unit_price) }}</td><td>{{ number_format($item->refund_amount) }}</td></tr>@endforeach</tbody><tfoot><tr><th colspan="7" class="text-end">جمع مبلغ بستانکاری</th><th>{{ number_format($document->refund_total) }} ریال</th></tr></tfoot></table></div><div class="p-3"><div class="signature-grid"><div class="signature-box">امضای ثبت‌کننده</div><div class="signature-box">امضای مالی</div><div class="signature-box">امضای انبار</div></div></div></div>
</div>
@endsection
