@extends('layouts.app')
@php use App\Models\SalesReturnDocument; use App\Models\SalesReturnDocumentItem; use Morilog\Jalali\Jalalian; $labels=SalesReturnDocument::statusLabels(); $sources=SalesReturnDocument::sourceTypeLabels(); @endphp
@section('content')
	<div class="container-fluid" dir="rtl">
		<div class="d-flex justify-content-between mb-3 flex-wrap gap-2"><div><h5>سند برگشت از فروش {{ $document->document_number }}</h5><div class="text-muted small">{{ $sources[$document->source_type] ?? '—' }} | {{ $document->created_at ? Jalalian::fromDateTime($document->created_at)->format('Y/m/d H:i') : '—' }}</div></div><div class="d-flex gap-2 flex-wrap">@if($document->isDraft())<a class="btn btn-sm btn-outline-primary" href="{{ route('sales-returns.edit',$document) }}">ویرایش</a><form method="POST" action="{{ route('sales-returns.apply',$document) }}">@csrf<button class="btn btn-sm btn-success">ارسال به صف انبار</button></form><form method="POST" action="{{ route('sales-returns.cancel',$document) }}">@csrf<button class="btn btn-sm btn-warning">لغو Draft</button></form>@endif<a class="btn btn-sm btn-outline-secondary" href="{{ route('sales-returns.print',$document) }}">چاپ</a>@if($document->isApplied())<a class="btn btn-sm btn-outline-danger" href="{{ route('sales-returns.pdf',$document) }}">PDF</a>@endif<a class="btn btn-sm btn-light" href="{{ route('sales-returns.index') }}">بازگشت</a></div></div>
		@if($document->isPendingWarehouse())<div class="alert alert-warning border mb-3"><strong>در انتظار دریافت انبار</strong><div class="small mt-1">این سند هنوز روی موجودی و حساب مشتری اثر نهایی نگذاشته است. پس از بررسی مدیر انبار، فقط تعداد تأییدشده وارد موجودی و سند نهایی می‌شود.</div></div>@endif
		<div class="row g-3 mb-3"><div class="col-md-4"><div class="card"><div class="card-body"><h6>اطلاعات سند</h6><div>وضعیت: <b>{{ $labels[$document->status] ?? '—' }}</b></div><div>مبلغ کل: {{ number_format($document->total_refund_amount) }}</div><div>تعداد کل: {{ number_format($document->total_quantity) }}</div><div>علت: {{ $document->return_reason ?: '—' }}</div></div></div></div><div class="col-md-4"><div class="card"><div class="card-body"><h6>مشتری</h6><div>{{ $document->customer?->display_name ?: '—' }}</div><div>{{ $document->customer?->mobile ?: '—' }}</div><div>کد: {{ $document->customer?->crm_customer_id ?: $document->customer_id }}</div><div>مانده فعلی: {{ number_format((int)($document->customer?->balance ?? 0)) }}</div></div></div></div><div class="col-md-4"><div class="card"><div class="card-body"><h6>مرجع</h6>@if($document->isInternal())<div>فاکتور داخلی: @if($document->invoice && $canViewSourceInvoice)<a href="{{ route('vouchers.sales.show',$document->invoice->uuid) }}">{{ $document->invoice->uuid }}</a>@elseif($document->invoice){{ $document->invoice->uuid }}@else — @endif</div>@else<div>فاکتور سازه‌حساب: {{ $document->external_invoice_number ?: '—' }}</div><div>تاریخ: {{ $document->external_invoice_date ? Jalalian::fromDateTime($document->external_invoice_date)->format('Y/m/d') : '—' }}</div>@endif<div>مرجع: {{ $document->reference_number ?: '—' }}</div></div></div></div></div>
		<div class="card mb-3"><div class="card-header bg-white fw-bold">اقلام</div><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>کالا</th><th>تنوع</th><th>کد</th><th>تعداد</th><th>وضعیت</th><th>مقصد</th><th>مبلغ واحد</th><th>مبلغ کل</th></tr></thead><tbody>@foreach($document->items as $item)<tr><td>{{ $item->product_name_snapshot ?: $item->product?->name }}</td><td>{{ $item->variant_name_snapshot ?: $item->variant?->variant_name }}</td><td>{{ $item->sku_snapshot ?: $item->barcode_snapshot ?: '—' }}</td><td>{{ number_format($item->return_quantity) }}</td><td>{{ SalesReturnDocumentItem::conditionLabels()[$item->item_condition]??'—' }}</td><td>{{ $item->destinationWarehouse?->name }}</td><td>{{ number_format($item->refund_unit_price) }}</td><td>{{ number_format($item->refund_amount) }}</td></tr>@endforeach</tbody></table></div></div>
		<div class="row g-3"><div class="col-md-6"><div class="card"><div class="card-body"><h6>Audit</h6><div>ایجادکننده: {{ $document->creator?->name ?: '—' }} | {{ $document->created_at ? Jalalian::fromDateTime($document->created_at)->format('Y/m/d H:i') : '—' }}</div><div>نهایی‌کننده: {{ $document->applier?->name ?: '—' }} | {{ $document->applied_at ? Jalalian::fromDateTime($document->applied_at)->format('Y/m/d H:i') : '—' }}</div>@if($document->isApplied())<div>Ledger Credit: {{ number_format($healthCheck['ledger_amount'] ?? 0) }}</div><div>Stock Movement count: {{ number_format($healthCheck['stock_movement_count'] ?? 0) }}</div>@endif</div></div></div><div class="col-md-6"><div class="card"><div class="card-body"><h6>وضعیت ثبت مالی و انباری</h6>@if($document->isPendingWarehouse())<div class="fw-bold text-warning">در انتظار تأیید مدیر انبار</div><div class="small text-muted">تا زمان تأیید صف، موجودی و بستانکاری مشتری ثبت نهایی نمی‌شود.</div>@elseif($document->isApplied())<div class="fw-bold {{ ($healthCheck['ok']??false)?'text-success':'text-danger' }}">{{ ($healthCheck['ok']??false)?'سالم':'نیاز به بررسی' }}</div>@foreach(($healthCheck['checks']??[]) as $name=>$ok)<div class="small">{{ $ok ? '✓' : '×' }} {{ $name }}</div>@endforeach<div class="text-muted small">این Health Check فقط خواندنی است و هیچ Sync یا Repair انجام نمی‌دهد.</div>@else<div class="text-muted">این سند هنوز ثبت نهایی نشده است.</div>@endif</div></div></div></div>
	</div>
@endsection
