@extends('layouts.app')
@section('content')
@php($labels=\App\Models\SalesReturnDocument::statusLabels()) @php($sources=\App\Models\SalesReturnDocument::sourceTypeLabels())
<div class="container-fluid" dir="rtl"><div class="d-flex justify-content-between mb-3"><h5>سند برگشت از فروش {{ $document->document_number }}</h5><div class="d-flex gap-2">@if($document->isDraft())<a class="btn btn-sm btn-outline-primary" href="{{ route('sales-returns.edit',$document) }}">ویرایش</a><form method="POST" action="{{ route('sales-returns.apply',$document) }}">@csrf<button class="btn btn-sm btn-success">ثبت نهایی</button></form><form method="POST" action="{{ route('sales-returns.cancel',$document) }}">@csrf<button class="btn btn-sm btn-warning">لغو Draft</button></form>@endif<a class="btn btn-sm btn-outline-secondary" href="{{ route('sales-returns.print',$document) }}">چاپ</a><a class="btn btn-sm btn-light" href="{{ route('sales-returns.create') }}">بازگشت</a></div></div>
@if(session('success'))<div class="alert alert-success small">{{ session('success') }}</div>@endif
<div class="row small g-2 mb-3"><div class="col-md-3">شماره سند: <b>{{ $document->document_number }}</b></div><div class="col-md-3">نوع: {{ $sources[$document->source_type]??$document->source_type }}</div><div class="col-md-3">وضعیت: {{ $labels[$document->status]??$document->status }}</div><div class="col-md-3">مشتری: {{ trim(($document->customer->first_name??'').' '.($document->customer->last_name??'')) }}</div><div class="col-md-3">فاکتور مرجع: {{ $document->invoice?->uuid ?: $document->external_invoice_number }}</div><div class="col-md-3">تاریخ مرجع: {{ $document->external_invoice_date?->format('Y-m-d') }}</div><div class="col-md-3">علت: {{ $document->return_reason }}</div><div class="col-md-3">ثبت‌کننده: {{ $document->creator?->name }}</div><div class="col-md-3">ثبت‌کننده نهایی: {{ $document->applier?->name }}</div><div class="col-md-3">تاریخ ثبت نهایی: {{ $document->applied_at?->format('Y-m-d H:i') }}</div><div class="col-12">توضیحات: {{ $document->description }}</div></div>
<table class="table table-sm"><thead><tr><th>کالا</th><th>تنوع</th><th>تعداد</th><th>وضعیت کالا</th><th>انبار مقصد</th><th>قیمت واحد بستانکاری</th><th>مبلغ کل</th></tr></thead><tbody>@foreach($document->items as $item)<tr><td>{{ $item->product_name_snapshot }}</td><td>{{ $item->variant_name_snapshot }}</td><td>{{ $item->return_quantity }}</td><td>{{ \App\Models\SalesReturnDocumentItem::conditionLabels()[$item->item_condition]??$item->item_condition }}</td><td>{{ $item->destinationWarehouse?->name }}</td><td>{{ number_format($item->refund_unit_price) }}</td><td>{{ number_format($item->refund_amount) }}</td></tr>@endforeach</tbody></table>
<div class="border rounded p-2 small">تعداد کل: {{ $document->total_quantity }} | مبلغ بستانکاری: {{ number_format($document->total_refund_amount) }} ریال | سالم: {{ $document->items->where('item_condition','healthy')->sum('return_quantity') }} | مرجوعی: {{ $document->items->where('item_condition','damaged')->sum('return_quantity') }}</div></div>
@endsection
