@extends('layouts.app')
@section('content')
<div class="container-fluid" dir="rtl">
 <div class="d-flex justify-content-between align-items-center mb-3"><h4 class="page-title mb-0">انبارگردانی</h4><a class="btn btn-primary" href="{{ route('stock-count-documents.create') }}">ثبت سند انبارگردانی محصولی</a></div>
 <div class="card"><div class="card-body table-responsive"><table class="table table-striped align-middle"><thead><tr><th>شماره سند</th><th>تاریخ</th><th>نوع</th><th>محصول/محدوده</th><th>انبار</th><th>تنوع</th><th>صفرشده</th><th>افزایش</th><th>کاهش</th><th>ثبت‌کننده</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>
 @forelse($documents as $doc)<tr><td>{{ $doc->document_number }}</td><td>{{ optional($doc->document_date)->format('Y-m-d') }}</td><td>{{ ($doc->type ?? 'product') === 'product' ? 'انبارگردانی محصولی' : 'انبارگردانی نقشه‌ای' }}</td><td>{{ $doc->product?->name ?? '—' }}</td><td>{{ $doc->warehouse?->name ?? '—' }}</td><td>{{ $doc->variants_count ?: $doc->items_count }}</td><td>{{ $doc->zeroed_count }}</td><td>{{ $doc->total_increase }}</td><td>{{ $doc->total_decrease }}</td><td>{{ $doc->creator?->name ?? '—' }}</td><td>@php($st=$doc->status)<span class="badge bg-{{ $st==='draft'?'warning':($st==='cancelled'?'secondary':'success') }}">{{ $st==='draft'?'پیش‌نویس':($st==='cancelled'?'لغوشده':'اعمال‌شده') }}</span></td><td class="text-nowrap"><a class="btn btn-sm btn-outline-primary" href="{{ route('stock-count-documents.view',$doc) }}">مشاهده</a>@if($doc->status==='draft') <a class="btn btn-sm btn-outline-success" href="{{ route('stock-count-documents.edit',$doc) }}">ادامه شمارش</a><form class="d-inline" method="post" action="{{ route('stock-count-documents.cancel',$doc) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-secondary">لغو پیش‌نویس</button></form>@endif @if($doc->status==='finalized')<button onclick="print()" class="btn btn-sm btn-outline-dark">چاپ</button>@endif</td></tr>@empty<tr><td colspan="12" class="text-center text-muted">سندی ثبت نشده است.</td></tr>@endforelse
 </tbody></table>{{ $documents->links() }}</div></div>
</div>
@endsection
